### ISSUE TITLE
[FR] Advanced Options for View Selector

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#100]
It would be great to have more options to customize the view selector. For example, changing the icon size, getting rid of the label, getting rid of the icon, etc.

Changing the icon size would be my first request as I can't seem to make the icons look good size wise in relation to the label.

**Comment by jimz011** [comment]
Expect major options for all addons soon, this will include everything you ask for in this issue!

**Comment by jimz011** [comment]
The view selector will be removed in favor of a state-switch, this should be a lot easier to program and will look a lot more logic! The end results should be roughly the same.

**Comment by jimz011** [comment]
Actually I have been looking through the code, and all that you ask for is already there.

You can already change the icon size, remove the icon or remove the name. Just do not define them. If you define them they will show. But if you only define a name there wont be an icon.
