### ISSUE TITLE
improvement from climate entities on sensor

### ISSUE THREAD

**Issue by zbuh** [jimz011/homekit-infused#101]
The improvement is to consider on, the AC units that have "AUTO" mode. aka heat_cool mode

      current_climate_entities_on:
        friendly_name: All Climate Entities Currently On
        value_template: >-
          {% set heat = expand('group.all_climate_entities')|selectattr('state','eq','heat')|list|count %}
          {% set cool = expand('group.all_climate_entities')|selectattr('state','eq','cool')|list|count %}
          {% set heat_cool = expand('group.all_climate_entities')|selectattr('state','eq','heat_cool')|list|count %}          
          {% set total = heat + cool + heat_cool %}
          {{ total }}

**Comment by jimz011** [comment]
Looks good, will merge this for the next release!

**Comment by jimz011** [comment]
Merged for v2021.11.1, will now close this
