### ISSUE TITLE
GUI-Sandbox archived

### ISSUE THREAD

**Issue by FelixGail** [jimz011/homekit-infused#104]
[Lovelace GUI Sandbox](https://github.com/thomasloven/lovelace-gui-sandbox), which is listed as a required addon is archived and can not be added trough HACS.

**Comment by jimz011** [comment]
Yes I had noticed, will remove the requirement next time. You dont need it though for HKI to operate. So you can safely skip it.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Felix Gail ***@***.***>
Sent: Thursday, July 15, 2021 5:27:42 PM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] GUI-Sandbox archived (#104)


Lovelace GUI Sandbox<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthomasloven%2Flovelace-gui-sandbox&data=04%7C01%7C%7Cb8530ea230694d97a65908d947a51703%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619596636009613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JgjSZoWoN9IIjGXZBy2bvKp3cxQmltNs%2BAyH9c2Wd38%3D&reserved=0>, which is listed as a required addon is archived and can not be added trough HACS.

**Comment by FelixGail** [comment]
Thank you for the fast reply
