### ISSUE TITLE
Error loading Configuration

### ISSUE THREAD

**Issue by mrachm** [jimz011/homekit-infused#106]
Hi,

I followed every step in the instructions to install HKI but when i press "check configuration" it says:

`Error loading /config/configuration.yaml: while scanning for the next token
found character '%' that cannot start any token
  in "/config/packages/hki-base/base.yaml", line 3, column 2`

In the Base.yaml the editor shows the following error:
`missed comma between flow collection entries at line 3, column 2:
    {% for name, data in _global.view ... 
     ^`

## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Etc/GMT

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 872
Installed Repositories | 23

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 28.6 GB
disk_used | 10.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), Visual Studio Code (3.6.2), Samba share (9.5.1), File editor (5.3.3), Terminal & SSH (9.1.3), Node-RED (10.0.0), Home Assistant Google Drive Backup (0.104.3), Spotify Connect (0.9.1), Zigbee2mqtt (1.21.0-4), RPC Shutdown (2.2), AdGuard Home (4.1.9), Portainer (2.0.0), Grafana (7.2.0), InfluxDB (4.1.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 19
views | 6
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by zroger49** [comment]
Have you installed all the required dependencies https://jimz011.github.io/homekit-infused/installation? 
Also, since jinja2 templates are used in the base.yaml file (and in many other yaml files in this package) vs-code trows several errors, but those are normal and the application will run

**Comment by mrachm** [comment]
yes they are installed and seem to work.

I don't know much about packages, so I simply created a folder "packages" into the config folder where I put the HKI files, could this be the problem?

**Comment by zroger49** [comment]
Likely. 
Here are the installation instructions: 

### Installation

- Copy the /hki-base/ folder to the root of your setup
- Copy the /hki-user/ folder to the root of your setup
- Copy the /packages/ folder to the root of your setup
- Copy everything in the /www folder to the /www folder in the root of your setup. If you do not have your own www/ folder already simply copy the download www/ folder

Where the root of your setup is the /config

you also have to add these lines in the configuration.yaml file 

```
homeassistant:
  packages: !include_dir_named packages/
```

I believe I'm not missing anything, but you check the instructions [here](https://jimz011.github.io/homekit-infused/installation#Installation) after the section with all requirements.

**Comment by mrachm** [comment]
Its working now. I ,ade a misstake at the www/ folder.
Thank you
