### ISSUE TITLE
Can't install required Add-ons (GUI Sandbox is archived)

### ISSUE THREAD

**Issue by ckambler** [jimz011/homekit-infused#108]
I'm trying to get homekit infused installed, most of the required add-ons work fine, either showing up in the default HACS list, or being added as their own separate sources under "custom repositories". However, the gui-sandbox add-on won't install, as the github repo is archived, and the HACS refuses to install it because it's archived. Do you know a way around this?

![image](https://user-images.githubusercontent.com/2066884/139304393-04bc3b63-5304-48c5-ab1a-98446d1bba38.png)

**Comment by jimz011** [comment]
Skip it, I need to remove it. The setup will load fine without it, it will just throw an error in the HKI Settings menu where the card is supposed to be.

**Comment by ckambler** [comment]
awesome, thanks!
