### ISSUE TITLE
Dwains Theme Dark (HKI Edition)

### ISSUE THREAD

**Issue by schol478** [jimz011/homekit-infused#110]
Hi Jim,

I'm using the theme Dwains Theme Dark (HKI Edition) (very nice!) but i want to change the color of the integration text.
Let me show you what i mean;

![afbeelding](https://user-images.githubusercontent.com/60742248/142384162-4d8daff6-861d-4038-9729-f97b1d24f168.png)
It is not possible to read the text because it's the same color. 
Also the selected button / text is a problem; 

![afbeelding](https://user-images.githubusercontent.com/60742248/142384316-2a46578d-c86d-4838-b5f4-7d50b7d63441.png)

What variables i need to change?

**Comment by henrikrox** [comment]
@schol478 did you figure this out? I'm having the exact same issues, that dark mode is blocking out some text

**Comment by jimz011** [comment]
I am working on this, though css is a real pain. I might rewrite the dark theme completely. Expect updates for this in this month. I am aiming for a december release for this. So stay tuned!

**Comment by jimz011** [comment]
This is fixed with the release of HKI 2021.12.3, closing this now!
