### ISSUE TITLE
Small bug with colors in themes

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#114]
With the light theme i still have this issue when going to a thermostat, pressing settings, and all the text is grey on black background.
![IMG_4002 (1)](https://user-images.githubusercontent.com/6884716/145825009-53e6cb10-36fb-4188-9fc2-6fb2bc323832.PNG)

Guess it should be white

Dont see any issues with dark theme anymore

**Comment by jimz011** [comment]
The popups will be theme specific soon, so I will not fix this

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: henrikrox ***@***.***>
Sent: Monday, December 13, 2021 2:55:49 PM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] Small bug with colors in themes (Issue #114)


With the light theme i still have this issue when going to a thermostat, pressing settings, and all the text is grey on black background.
[IMG_4002 (1)]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6884716%2F145825009-53e6cb10-36fb-4188-9fc2-6fb2bc323832.PNG&data=04%7C01%7C%7C0f4e654990334d1dc67c08d9be404597%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637750005511796623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hLlaBvQC74xcSgKRAz6h%2FetaoPei%2BSGkWP1IOOmi0KQ%3D&reserved=0>

Guess it should be white

Dont see any issues with dark theme anymore

**Comment by jimz011** [comment]
This is fixed in HKI 5, closing this issue now
