### ISSUE TITLE
[FR] Question/Suggestion about layout

### ISSUE THREAD

**Issue by jjsapido** [jimz011/homekit-infused#117]
I really appreciate your hard work, and the dashboard is pretty nice. I tried to work with it but I'm currently stuck in layout configuration. I read the code behind and if I understood correctly it's working like this:

```
{% for name, data in _global.view_config.items() %}
## for each view (name) and its array of addons/cards (data)
  {% if data.simple_weather is defined %}
  {% for content in data.simple_weather %}
  # if an addon is defined print the corresponding template for each entity inside
``` 

which in turn makes it impossible to decide the order of presentation of the addons (unless reordering the base.yaml file, which however still results in a hardwired ordering, and the impossibility to separate groups of entities of the same type) 

so I'm wondering if you possibly plan to reorganize the code in future versions to do something like this:

``` 
{% for name, data in _global.view_config.items() %}
## for each view (name) and its array of addons/cards (data)
  {% for addon in data %}
  ## for each addon, following his appearence order
    {% switch-case the list of addons template %}
    # select the proper template
      {% for content in data.simple_weather %}
      # and print the corresponding template for each entity inside
``` 

thanks

**Comment by jimz011** [comment]
This looks very good and something I have been looking for, however I am not a programmer. I did this in my spare time over the past 3 years. I am looking at the example to understand a bit what you want, though I might need a bit help with setting this up. I will definitely look into this as this would make HKI a lot better.

I have added grid-area options for the upcoming release to most addons, I have tested it and that works so that at least is something. However I feel that grid settings are very hard for the people that just want a nice looking dashboard without too much effort. So this would definitely be a great addition. I also plan to make the config slightly different which would look something like this:

```yaml
my_view:
  title: My View
  icon: mdi:home
  addons:
    devices:
      - title: my devices
```
This would make reading the code slightly easier.

**Comment by jjsapido** [comment]
Hello thanks for considering this, i can help you somehow, unfortunately, I'm not an expert in using jinja/yaml templating.. That means I really don't know at the moment how to access and watch the content of data structures like `_global.view_config.items()`

I can take a look at it but I have very much limited spare time in these weeks, if you can describe me the shape of an entry in `_global.view_config.items()` i could be more precise

Just to make my point clearer from higher-level perspective:
you currently  parse each view by searching for an addon-type
``` {% if data.simple_weather is defined %} ```
then cycling through all the elements of that addon-type
``` {% for content in data.simple_weather %} ```

I'm suggesting to sequentially cycle through the entities 
```  {% for myaddon in data %} ```
and each time you encounter an entity you simply invoke the correct method to render it according to its type.
``` {% switch-case the list of addons template %} ``` 
can be rephrased like:
```  {% if myaddon.simple_weather is defined %} ```

My only concern is the structure / shape of your `data` variable...
if data is an associative array there's a problem since it loses its sequential shape, otherwise if `data`is a simple list/array the transition is straightforward.

example:
```
my_view:
  title: My View
  icon: mdi:home
  addon1:
       device 1
  addon2:
  addon1:
       device 2
```
**associative array** means your `data` variable resembles something like this:
```
data
 - addon1
     -  device 1
     - device 2
 - addon2
```
thus grouping element in subgroups according to some properties (i.e., addon type), which makes impossible to follow the initial ordering (in this example devices 1 and 2 are part of addon1 subgroup thus thei woul appear sequentialli in a loop even if they werent sequential in initial wiev descriptor.

**sequential array**  means your `data` variable resembles something like this:
```
data
   -  addon1 - device 1
   - addon2
   - addon1 - device 2
```
thus respecting the order of the view descriptor

Hope this makes my point a little clearer

**Comment by jimz011** [comment]
The point is clear, I just do not know if this is possible. I did consider making it like that, though it did not turn out the way I imagined. I will try again soon since well..... I am rewriting HKI anyways.

**Comment by jjsapido** [comment]
just in case,  if I can help you somehow just send me a line here, of course If you can provide me some data dump, like print of contents of variables, it would make me able to help better. thanks for all your effort

**Comment by jimz011** [comment]
Just wanted to say that I am currently working on this, it will take a few more weeks before it is finished, but it should have a ton of new layout options available!

**Comment by jimz011** [comment]
I am going to close this issue since I have just been able to build this, I have tested it and it is working. The order will be decided by the order you place them in.

You can expect this feature together with the improved layout features in HKI 5!
