### ISSUE TITLE
Orange Darkness.yaml contains duplicate key

### ISSUE THREAD

**Issue by Zippiejwz** [jimz011/homekit-infused#119]
Looks like a minor issue: 

YAML file /config/packages/homekit_infused/../../hki-base/themes/Orange Darkness.yaml contains duplicate key "app-header-background-color". Check lines 335 and 343

easy to solve on my end.

**Comment by jimz011** [comment]
All themes might get removed within the very near future. Which will hold a master theme where you can style most elements yourself via the UI.

I am currently testing this and it looks very promising.

![Screenshot_20220122-164203_Home Assistant.jpg](https://user-images.githubusercontent.com/47046878/150645412-87ead053-21b7-4325-b502-2aa4d9f555bb.jpg)

**Comment by jimz011** [comment]
Closing this issue since this is no longer an issue in the upcoming HKI 5
