### ISSUE TITLE
hello ,i copy your config , but 

### ISSUE THREAD

**Issue by litianyu0707** [jimz011/homekit-infused#120]
![image](https://user-images.githubusercontent.com/22993989/150676655-14954871-f0b1-4f98-9c53-a0efd2a15a1f.png)
![image](https://user-images.githubusercontent.com/22993989/150676685-ad52a6ce-8a67-4f59-9ced-cb7931305fe1.png)

how can i fix it?  thank you!

**Comment by jimz011** [comment]
Please share the bottom part of the error message. The top part is not very useful, since the actual error is not mentioned there.

**Comment by litianyu0707** [comment]
Hello , thank you for your help!  

![image](https://user-images.githubusercontent.com/22993989/150754788-5e7bc60b-5731-4a43-9d5f-387df66d13f3.png)
![image](https://user-images.githubusercontent.com/22993989/150754876-7851dada-7c92-4724-8017-04e08487ef9b.png)
![image](https://user-images.githubusercontent.com/22993989/150754973-4a1f694a-105a-43bd-8fe3-f9f016e46195.png)

@jimz011

**Comment by jimz011** [comment]
Show your code as well, also do NOT use special characters in object names. Use the title field for that if you have to use special characters.

**Comment by jimz011** [comment]
is this still an issue?

**Comment by jimz011** [comment]
Closed because no more replies on this issue.
