### ISSUE TITLE
devices addon doesn't support simple dimmers.

### ISSUE THREAD

**Issue by ghost** [jimz011/homekit-infused#126]
I have simple dimmers (no rgb or cct) , and when using the "devices" addon, the resulting pop-up is a switch. Current types are rgb, color-temp, switch, sensor or fan, is it possible to add a "dimmer" type? 
For now i have it set to color-temp

**Comment by jimz011** [comment]
This will be fixed in the next release!

**Comment by jimz011** [comment]
Fixed in HKI 5, will close this now
