### ISSUE TITLE
After setup as per instructions get a invalid config message

### ISSUE THREAD

**Issue by Rayeliint** [jimz011/homekit-infused#133]
Hi there, have installed as per your docs but just checking the config validation I get the error "Package hki_configuration setup failed. Component lovelace has duplicate key 'mode'"
Can you help please?

**Comment by jimz011** [comment]
Don't define lovelace mode in your configuration.yaml, just remove that line

**Comment by Rayeliint** [comment]
Thanks jimz011, worked a treat!
