### ISSUE TITLE
[FR] color badge/label/icon

### ISSUE THREAD

**Issue by Dakul05** [jimz011/homekit-infused#134]
Hi there, 
new version on its way, and unaware whats inside it.
Feature request

Wouldnt it be awsome if we could color the badge/label/icon (one of them or all induvidual) from within the view_config.yaml
by a simple code like below or something?

In my case im using the button label to show current temperatur in each room, and would be great to see at menu/start -screen level how things are. (4 teens behind closed doors that during winter like it to be HOT and during summer COLD, but not contributing to the energy bills)
```
    styles:
      label:
      - color: "[[[ if (states['sensor.room_temperature_2'].state > 22) return 'red'; else return 'green']]]"

```

**Comment by jimz011** [comment]
This is already possible in HKI 5
