### ISSUE TITLE
Picture glance card

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#135]
Hi, I've discovered that the "picture glance card" is way more stable and gives me a constant live feed of my cameras as I want, better than the built-in to HKI "camera" integration, as that one just takes a long time to load and buffers a lot, compared to the "picture glance card" which doesn't buffer with my live cam feeds.

So just wondering how I can add this card to HKI because what I've done doesn't seem to be working, because I have 4 cams and this would be perfect for the dashboard. Thanks. 

What I tried, that did not work:

<img width="335" alt="Screen Shot 2022-03-06 at 3 38 56 AM" src="https://user-images.githubusercontent.com/3034555/156915596-3f594014-483a-4b55-981a-d19600df162d.png"> 

My file: 
[ezyzip.zip](https://github.com/jimz011/homekit-infused/files/8192488/ezyzip.zip)

(btw, wasn't sure how to add the "help-wanted" tag so I just made an issue)

**Comment by jimz011** [comment]
You should use the custom addon if you want to add other cards that are not within the addons in HKI. 

However, I want to point out to you that the camera's addon in HKI is literally a picture-glance card 😂 

![image](https://user-images.githubusercontent.com/47046878/156938353-f2091c1c-865d-404f-bc9f-9331ac6d9ef3.png)

As you can see in the code in the screenshot.

**Comment by dnestico** [comment]
Oh LOL, that's so weird cuz when I have the cameras in the "camera" plugin they buffer alot and take along time to load, when I put them in the "picture glance card" they didn't and showed me a perfect live feed.

Strange but thanks I'll try this out.

**Comment by dnestico** [comment]
Not sure why it's not working, I probably made the smallest mistake you'll notice in 2 seconds lol.

<img width="427" alt="Screen Shot 2022-03-06 at 6 38 48 PM" src="https://user-images.githubusercontent.com/3034555/156947289-4aafe4b5-1045-4dd2-8a39-275d26bb65ff.png">
<img width="323" alt="Screen Shot 2022-03-06 at 6 38 59 PM" src="https://user-images.githubusercontent.com/3034555/156947293-36e361e9-a857-44ed-88c2-7b257736a7aa.png">

My file: 
[ezyzip.zip](https://github.com/jimz011/homekit-infused/files/8193776/ezyzip.zip)

**Comment by jimz011** [comment]
Yes YAML is very strict on spacing, under custom you have used 3 spaces instead of 2

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dnestico** [comment]
Yea I'm sorry but I went back and made it 2 spaces and am still not sure what's wrong.

<img width="317" alt="Screen Shot 2022-03-06 at 6 57 53 PM" src="https://user-images.githubusercontent.com/3034555/156947982-28290218-d49b-4673-a47a-5d4062e88eeb.png">
-
<img width="939" alt="Screen Shot 2022-03-06 at 6 57 36 PM" src="https://user-images.githubusercontent.com/3034555/156947992-2a5296f4-b3c7-47c5-8a0f-580913868aaa.png">

My file:
[ezyzip.zip](https://github.com/jimz011/homekit-infused/files/8193832/ezyzip.zip)

**Comment by jimz011** [comment]
You must define the entities as a list

```yaml
entities:
  - camera.office
  - camera.kitchen
```

**Comment by dnestico** [comment]
Yea this card just hates me unfortunately lol

<img width="276" alt="Screen Shot 2022-03-06 at 7 10 54 PM" src="https://user-images.githubusercontent.com/3034555/156948454-cd9b84da-ef44-463e-8006-e0d77c590584.png">
<img width="325" alt="Screen Shot 2022-03-06 at 7 11 00 PM" src="https://user-images.githubusercontent.com/3034555/156948459-1bb9b11f-767c-4538-b34c-340486e3a90c.png">

**Comment by jimz011** [comment]
My bad, you are using custom with picture glance. You can only use a single entity.

Try:
```yaml
custom:
  - title: Camera
    cards:
      - type: picture-glance
        entity: camera.ffmpeg
```
Also please try to use code blocks instead of screenshots. Its a real pain in the proverbial behind to rewrite every piece of code to help instead of just copy/pasting.

**Comment by dnestico** [comment]
I copied your code and still not working, no idea why none of this is working.

<img width="275" alt="Screen Shot 2022-03-06 at 7 40 30 PM" src="https://user-images.githubusercontent.com/3034555/156949848-5c45e7a1-8c16-45e7-a9f9-4c0e287142a8.png"> 

(tried the code block thing)

```    
  custom:
      - title: Camera
        cards:
          - type: picture-glance
            entity: camera.ffmpeg
```  

[ezyzip.zip](https://github.com/jimz011/homekit-infused/files/8193951/ezyzip.zip)

**Comment by dnestico** [comment]
Update: I figured it out!

This is what worked.

<img width="278" alt="Screen Shot 2022-03-12 at 4 31 45 AM" src="https://user-images.githubusercontent.com/3034555/158012577-473711e6-d473-4511-a8d7-e26d9193e23b.png">

Result: (and for some reason a much smoother stream for me)

<img width="388" alt="Screen Shot 2022-03-12 at 4 27 39 AM" src="https://user-images.githubusercontent.com/3034555/158012600-16dc6230-b526-4ba1-bc2a-1318ddf6d87c.png">

**Comment by jimz011** [comment]
👍😃

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
