### ISSUE TITLE
Hide notification bar at top

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#137]
Sorry if this has been answered before, just wondering it's possible to hide the notification at the top "Front Door unlocked/locked" in certain rooms. 

I'd like it in the main room but don't need it in my other rooms. Thanks.

<img width="1144" alt="Screen Shot 2022-03-12 at 5 01 04 AM" src="https://user-images.githubusercontent.com/3034555/158013574-c5582f38-b6ca-4c06-8b20-2b9ca2242256.png">

**Comment by jimz011** [comment]
Yes, define a subtitle for that room.

**Comment by jimz011** [comment]
Alternatively you can set: `show_subtitle: false` for that room.

**Comment by dnestico** [comment]
Thanks!

**Comment by janstadt** [comment]
I've set `show_subtitle: false` for my views but i still see the in the subtitle. Any way to get rid of that? 
![image](https://user-images.githubusercontent.com/1872087/162053236-28c08011-6206-470a-b2ae-8422f0022ac0.png)

**Comment by jimz011** [comment]
Edit: disregard what I said, I will look into it!

**Comment by dnestico** [comment]
I did this and it worked.

home:
    title: David's Room
    icon: mdi:alpha-d-circle
    show_header: false
    show_in_navbar: true
    show_in_menu: true
    welcome_message: false

<img width="324" alt="Screen Shot 2022-04-06 at 3 39 33 PM" src="https://user-images.githubusercontent.com/3034555/162056595-54d5941d-868c-42db-826a-1d0e1286414d.png">

**Comment by jimz011** [comment]
But show_header would hide the entire header, not just the subtitle correct?

If not then I will need to change this, since well, just as I look at it it looks unlogical

**Comment by janstadt** [comment]
@jimz011 sounds good. Keep me posted on what you determine!

**Comment by dnestico** [comment]
@jimz011  It did this sorry

<img width="1202" alt="Screen Shot 2022-04-06 at 3 42 39 PM" src="https://user-images.githubusercontent.com/3034555/162057394-61f58629-63ac-4ac2-a991-3e69be60cedb.png">

**Comment by jimz011** [comment]
Ok, well it seems I did change the setting but not change the documentation.

@janstadt try the following:

```yaml
  my_view:
    title: Test View
    subtitle: hide
```
@dnestico exactly, it hides the HKI header completely.

@janstadt wants to hide the subtitle only, so try the code above.

**Comment by jimz011** [comment]
@dnestico Just a question, you are running HKI 4 correct?

Since I am looking through the code and see that the hide header part has been removed from HKI 5 entirely (I never added it back in). I will add it back in though, since well it was missing.

I am also guessing @janstadt is using HKI 5 which had some of the configuration variables slightly modified.

**Comment by dnestico** [comment]
Yes, I am still running HKI 4, not sure when or if I'll upgrade as I don't have much time atm but HKI 4 is still working just fine for me.

**Comment by jimz011** [comment]
That is what got me confused a bit. No worries, HKI 4 works fine for now, it will continue to work until it breaks. And by then I will look at the extent of the break and decide whether or not I will hotfix it or send it to the software graveyard.

**Comment by janstadt** [comment]
@jimz011 correct, running HKI5.

**Comment by jimz011** [comment]
@janstadt try the above and let me know if it worked for you, I just tested it and works for me.

**Comment by jimz011** [comment]
Lastly, I have changed the docs for HKI 5 so it should now reflect the correct settings. Note that hiding the title has also been added (but this will work after this weeks update).

**Comment by janstadt** [comment]
Since i have you here @jimz011 im trying to mess with the theming and i cannot seem to find the `HKI Settings` or `HKI Custom` mentioned here: https://jimz011.github.io/homekit-infused/addons/themes.html

I can however flip between the two themes that come for free (Light and Dark). Any ideas how to get to these settings?

**Comment by jimz011** [comment]
Click on the profile button (top right) and swipe through the top bar.

![Screenshot_20220406-222011_Home Assistant.jpg](https://user-images.githubusercontent.com/47046878/162063928-c9d25e1c-a1b0-4275-bde2-f413db1b514f.jpg)

Red arrow shows where it is, blue arrow indicates you can swipe this bar.

**Comment by janstadt** [comment]
AHHHHH! I didnt see any left/right arrows up there so i didnt realize there was more than i was seeing! Many thanks once again!
