### ISSUE TITLE
Thermostat popup icons

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#140]
It seems there should be icons here but they don't show? (where the circle is at the bottom)

<img width="408" alt="Screen Shot 2022-03-28 at 10 54 59 PM" src="https://user-images.githubusercontent.com/3034555/160523808-3dc39f36-8674-4590-b89e-d22a8206db27.png">

	card:
    type: vertical-stack
    cards:
      - type: custom:thermostat-popup-card
        entity: climate.3family_room
        settingsPosition: bottom
        settings: true
        fullscreen: false

**Comment by jimz011** [comment]
Uninstall this card and get the correct one. As shown in the documentation.
You need to add the repository as a custom repo in HACS and then install the correct card from jimz011 repo. Not the one from Dbuit.

**Comment by dnestico** [comment]
Thank you, that fixed it!

One final question before I probably upgrade to HKI 5.

I am trying out some new buttons and I want them beside each other (horizontal stack), I got one horizontal stack to work, now I want multiple stacks, but it isn't working and I've been looking at the docs to try and get help but can't figure it out, please help.

<img width="822" alt="Screen Shot 2022-03-29 at 3 21 37 AM" src="https://user-images.githubusercontent.com/3034555/160556136-35ea13ec-e2da-46a0-90b6-929c81fb3d3d.png">


I tried the code blocks thing by the way and it just won't format it right for whatever reason.

**Comment by jimz011** [comment]
well, the error tells you exactly what is wrong, bad indentation, all is fine except the second horizontal stack line.

**Comment by dnestico** [comment]
Figured it out, thanks. 

damn yaml can be frustrating sometimes haha.
