### ISSUE TITLE
Certain Popup Cards Not Working

### ISSUE THREAD

**Issue by InfiniteBed** [jimz011/homekit-infused#141]
Hello, 
Several of my popup cards are not working, only showing inline error messages. If need be I can send configs.
![image](https://user-images.githubusercontent.com/50598242/160918024-36d752b5-26ec-4380-8eff-91fce91f690e.png)
![image](https://user-images.githubusercontent.com/50598242/160918113-4572ab98-d407-41a3-9c08-f6a350e95c5a.png)

**Comment by jimz011** [comment]
Did you install the light-popup-card?

**Comment by jimz011** [comment]
Did you install the light-popup-card and the more-info-card?
![Screenshot_20220330-220656_Chrome.jpg](https://user-images.githubusercontent.com/47046878/160921781-6179f61e-6a10-4642-ab8c-06356ee25298.jpg)

**Comment by InfiniteBed** [comment]
Well, would you look at that.
I have not, sorry for my ignorance :/
