### ISSUE TITLE
Implementation break with use_x_forwarded_for: true

### ISSUE THREAD

**Issue by teachers-petgoat** [jimz011/homekit-infused#142]
There's a weird bug i don't know how to fix. 
I'm using this in my configuration because i have multiple webserver in my homenetwork:
`http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.30`
  
if i use my local ip everthing looks nice:
![local](https://user-images.githubusercontent.com/37237884/161822442-86eeacbb-7775-479e-8720-40a4f6f39983.jpg)

but via the external dns the design breaks:
![Inkedhk_ssl_LI](https://user-images.githubusercontent.com/37237884/161822539-74680fee-2af2-441d-bc52-f6205424b281.jpg)

**Comment by teachers-petgoat** [comment]
reinstalled everything, now not even local works

issue can be deleted

**Comment by jimz011** [comment]
So I can close this?
Edit: you have already closed it 🤣


Btw, I really like the button style you have setup.

**Comment by teachers-petgoat** [comment]
thanks, i hope i figure out the issue, because your project is a really cool foundation
