### ISSUE TITLE
[Question] Use variables in views.yaml

### ISSUE THREAD

**Issue by MikeTheCleric** [jimz011/homekit-infused#148]
Hi! I've got a problem. I want to use some variables defined by me cycled using Jinja template (like the files in hki base folder, for example "base.yaml") in the views.yaml to make dynamic my configuration. Is it possible?

Thanks in advice!

**Comment by jimz011** [comment]
Hi, you can only use custom templates by using for example decluttering-card. If you want to use lovelace_gen you must disable addons on that view and setup `custom_legacy`. You can then use your own templates that you can save inside the user folder.
