### ISSUE TITLE
custom element doesn't exist

### ISSUE THREAD

**Issue by p51d8102** [jimz011/homekit-infused#152]
All of my light pop ups throw the error that the custom element doesn't exist.  I have tried reinstalling all of the components thru HACS with no luck.  What am I missing?  Even the binary sensor pop ups have an error above the history showing that the custom element doesn't exist

**Comment by jimz011** [comment]
Go to your resources tab and see if the resources were loaded.

For a video about this check https://youtu.be/MjTU25K-NkI

The part you are looking for starts at 05.50

**Comment by p51d8102** [comment]
They are all there with a ?hacstag=####### parameter after them.  Should I delete them all and try redownloading?  It's just the cards that are frontend repositories that need the resources correct?

**Comment by jimz011** [comment]
Yes only the frontend ones.  But hacsfiles is good. So leave that. 

Try opening it in an incognito window.  If that works,  then clear your cache.

**Comment by p51d8102** [comment]
Same result in incognito window.  I tried Chrome and Edge after clearing the cache with the same results.  I get the errors in the iOS app as well

**Comment by jimz011** [comment]
Do you have other dashboards installed? It seems that your browser isn't loading up the resources. I have some other closed issues that address this, but they all got it fixed by reinstalling everything.

Not sure why you are not able to see them, unless you run an old iOS version (did you test it on a desktop for example? Or did you just try it on your phone?).

Note that for this to work properly a minimum of iOS 14 is required, this is because HKI uses css values that were not available yet pre iOS 14. If you are using iOS 9.3.5 (which for some devices is the last iOS available) then well you are entirely out of luck since iOS 9 does not support ES6 which most HACS addons are using.

**Comment by p51d8102** [comment]
So I removed all of the front end and integration components listed on the installation instructions and reinstalled them 1 by 1.  I verified all of the resources are there and I still get the same error.  I tried using Chrome on my iPad & laptop and the iOS app on the phone after clearing the cache on each device with the same results.

**Comment by jimz011** [comment]
At this point I would say share your configuration.yaml file (you can do it over discord if you prefer to do it privately)

**Comment by jimz011** [comment]
hm wait, did you install all of the addons? or just the hacs addons from the installation page?

**Comment by jimz011** [comment]
As in, did you also install these?

![image](https://user-images.githubusercontent.com/47046878/164944957-73abdf7d-aac3-443c-bd13-f2c096b73668.png)

**Comment by p51d8102** [comment]
That was the problem...I did not have the AddOn Button components installed

**Comment by jimz011** [comment]
👍

**Comment by p51d8102** [comment]
Jimmy,

I have a separate question/feature request if necessary.  I have 3 Nest
thermostats and I have had to modify the hki_sensors.yaml file b/c of the
state that Nest reports back and only wanting the counter to show me the
HVAC units that are actually running (heating or cooling).  Of course
whenever I do a HKI update it overwrites this file in the
packaqes directory.  Just wanted to get your thoughts/ideas so that Nest
users could benefit from your dashboard.  Great product BTW!

Steve

This is the yaml that I changed:

      current_climate_entities_on:
#        friendly_name: All Climate Entities Currently On
#        value_template: >-
#          {% set heat =
expand('group.all_climate_entities')|selectattr('state','eq','heat')|list|count
%}
#          {% set cool =
expand('group.all_climate_entities')|selectattr('state','eq','cool')|list|count
%}
#          {% set heat_cool =
expand('group.all_climate_entities')|selectattr('state','eq','heat_cool')|list|count
%}
#          {% set total = heat + cool + heat_cool %}
#          {{ total }}
        friendly_name: All Climate Entities Currently On
        value_template: >-
          {% set heat = (is_state_attr('climate.downstairs', 'hvac_action',
'heating')) + (is_state_attr('climate.front', 'hvac_action', 'heating')) +
(is_state_attr('climate.back', 'hvac_action', 'heating')) %}
          {% set cool = (is_state_attr('climate.downstairs', 'hvac_action',
'cooling')) + (is_state_attr('climate.front', 'hvac_action', 'cooling')) +
(is_state_attr('climate.back', 'hvac_action', 'cooling')) %}
          {% set total = heat + cool %}
          {{ total }}

**Comment by jimz011** [comment]
Try to use code blocks in the future:

```yaml
      current_climate_entities_on:
#        friendly_name: All Climate Entities Currently On
#        value_template: >-
#          {% set heat =
expand('group.all_climate_entities')|selectattr('state','eq','heat')|list|count
%}
#          {% set cool =
expand('group.all_climate_entities')|selectattr('state','eq','cool')|list|count
%}
#          {% set heat_cool =
expand('group.all_climate_entities')|selectattr('state','eq','heat_cool')|list|count
%}
#          {% set total = heat + cool + heat_cool %}
#          {{ total }}
        friendly_name: All Climate Entities Currently On
        value_template: >-
          {% set heat = (is_state_attr('climate.downstairs', 'hvac_action',
'heating')) + (is_state_attr('climate.front', 'hvac_action', 'heating')) +
(is_state_attr('climate.back', 'hvac_action', 'heating')) %}
          {% set cool = (is_state_attr('climate.downstairs', 'hvac_action',
'cooling')) + (is_state_attr('climate.front', 'hvac_action', 'cooling')) +
(is_state_attr('climate.back', 'hvac_action', 'cooling')) %}
          {% set total = heat + cool %}
          {{ total }}
 ```

**Comment by jimz011** [comment]
```yaml
like: this
```
![image](https://user-images.githubusercontent.com/47046878/165151478-254c9ae8-5afd-43cf-834f-55e572fefa9f.png)

**Comment by p51d8102** [comment]
Jimmy,

My iOS is 15.4 so that shouldn’t be the issue. I don’t have any other
dashboards installed so let me wipe out all of the components and reinstall
them later today. I’ll let you know asap.

Thanks

Steve

**Comment by jimz011** [comment]
Yes just the frontend ones. But don't delete them.  They are fine.

Try an incognito window. If that works,  then clear your cache.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by p51d8102** [comment]
I just installed the HACS addons...looks like I need to install those
others b/c those names relate to my errors.  How did I miss that?
