### ISSUE TITLE
error when using the media players view

### ISSUE THREAD

**Issue by TheBoxTrot** [jimz011/homekit-infused#154]
ive been using you premade media view as a template and replacing all the entities in it with my own but I'm unsure what is causing this and if I'm missing an addon or something like that 

butoncardjsttemplateerror: typeerror: cannot read properties of undefined{reading 'state'} in 'if(states['sensor.media_players_playing'].state=='Playing')return'A media player is playing r.......

**Comment by jimz011** [comment]
If you just copied my config, then it won't work since you are missing the media players playing sensor.

Just remove or comment out the button_badge lines in your setup from the mediaplayers pages.

This media player sensor was not included with the setup, simply because it is too complicated.
