### ISSUE TITLE
Find My page map doesn't load unless another dashboard is loaded 

### ISSUE THREAD

**Issue by TheBoxTrot** [jimz011/homekit-infused#162]
so in order to get the find my page map to show up, I have to open the find my page then close it open another dashboard on the sidebar, then I can go back and open the find my page and then the map appears

**Comment by jimz011** [comment]
Yeah for some reason the map addon also breaks. Dont know what is causing it, but I have a feeling that it is because of css modding. I will keep this issue open for now.

**Comment by jimz011** [comment]
I think I have finally found a solution after months of trying other stuff.

This will be fixed in the next update!
