### ISSUE TITLE
Where is the "hki_settings" "ha_settings" "about"?

### ISSUE THREAD

**Issue by wedone** [jimz011/homekit-infused#163]
HKI5 v2022.4.1 without "hki_settings" "ha_settings" "about"？
![IMG_20220519_014018](https://user-images.githubusercontent.com/1226460/169634284-52bcefb8-b2cd-4e51-8eef-f7dbc301ba06.png)

**Comment by E020** [comment]
It behind this icon:
![CA64CADB-0EEB-40D9-A6B2-0E0A2E75383F](https://user-images.githubusercontent.com/57673156/169634835-9a420381-22e4-4606-90d8-8f19d74e61d5.jpeg)

Click to see about:
![E47F91DA-E9EC-43A1-AEDB-11F9480D269B](https://user-images.githubusercontent.com/57673156/169634889-11b87433-db94-49a9-be5c-b90191347770.jpeg)

Scroll to the left to see the HKI settings:
![AAE7DEAB-2511-4531-B8CC-3434431CE6F4](https://user-images.githubusercontent.com/57673156/169634907-6d714442-05cf-449c-a559-88bf5efa929e.jpeg)

**Comment by wedone** [comment]
thank you very much
