### ISSUE TITLE
Problem with badges in the header

### ISSUE THREAD

**Issue by donhimol** [jimz011/homekit-infused#165]
I just went from 4 to 5 (clean install) and I have an issue with header and badges on my mobile. Screenshot below. 
It seams that they are vertical not horizontal.
![obrazek PNG](https://user-images.githubusercontent.com/46449740/172454741-e33cbab4-76df-4e6f-8afe-ce0c90993a0a.png)

I was looking for a setting for whole day and I give up!

**Comment by jimz011** [comment]
Please state what OS and browser you are using to view your dashboard (not the OS your Home Assistant runs on)

**Comment by donhimol** [comment]
Home Assistant App on iOS.

On Chrome and Safari from iOS it looks better: 
![obrazek PNG](https://user-images.githubusercontent.com/46449740/172457229-2d78b802-2789-45c8-bf2a-2d6f81bf5b61.png)

**Comment by jimz011** [comment]
Looks like a caching error to me

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by donhimol** [comment]
Yep, you are right!
Thanks

**Comment by jimz011** [comment]
Great, just make sure you get the beta version of button card, otherwise you can't use the popups in HKI and thus also not reach the settings page.

In HACS click on button card and check `show beta versions`. If you already have button card installed, you can click on `redownload` and then select the new version.

**Comment by robinwalas** [comment]
![Schermafbeelding 2022-06-07 om 21 36 24](https://user-images.githubusercontent.com/70822027/172467458-c4cae841-4b62-4c64-8197-32ab74cdd2c1.png)
I've got this problem also. Clearing cache won't help. 
Chrome on Macos and also on the ios ha app. 
Anything else i can try?
