### ISSUE TITLE
[Question] Conditionality of each button in stack

### ISSUE THREAD

**Issue by donhimol** [jimz011/homekit-infused#166]
Is there a possibility use addons in the stack?

I want to have buttons for 15 different pollens grouped into one stack and make conditional visibility of each button only if pollen is other than low. I know I can do such conditionality for the stack but for each button (in the stack) seperatly?

**Comment by jimz011** [comment]
Unfortunately that isn't possible, however you can set templates in the buttons so it will show you different data depending on the template set. It is pretty advanced stuff though,  but if you know your way a bit with button card you might be able to create something like that.

Alternatively,  you could create different stacks depending on state.
