### ISSUE TITLE
Problem with badges in header 

### ISSUE THREAD

**Issue by robinwalas** [jimz011/homekit-infused#167]
Hi,
I've got a problem with the badges in the header. I've already cleared the caches but it won't help. 
I'm using Chrome on MacOS and the HA app on iOS. 
Anything else i can try?

Thanks for helping me out. 

![Schermafbeelding 2022-06-07 om 21 36 24](https://user-images.githubusercontent.com/70822027/172684475-13dca2e1-3c40-46a4-a7f9-89d967b9cc47.png)

**Comment by jimz011** [comment]
The header doesn't work well on iOS 13 or older. This is because HKI 5 uses css unsupported in older versions of Safari.

Please state which iOS version you are running.

**Comment by robinwalas** [comment]
> The header doesn't work well on iOS 13 or older. This is because HKI 5 uses css unsupported in older versions of Safari.
> 
> Please state which iOS version you are running.

Hi, using iOS 15.5 
First time using HKI 5. 

Thx

**Comment by robinwalas** [comment]
> The header doesn't work well on iOS 13 or older. This is because HKI 5 uses css unsupported in older versions of Safari.
> 
> Please state which iOS version you are running.

Hi, sorry for the "closed, reopened" stuff. 

I'm using IOS15.5
First time using HKI 5.

**Comment by jimz011** [comment]
Hm, iOS 15 should work fine. Did you change anything in the /hki-user/config/config.yaml file?

If yes please share the code here. If no, try redownloading Layout-Card and clear cache.

If nothing helps, there is one (ugly) solution and that is to comment out all the header badges in the mentioned config.yaml file as well as turn off the alarm badge.
It isnt a great solution, but it should at least give you a somewhat usable header.

I don't have iOS devices (other than some really old ones) to test, so it is hard for me to troubleshoot.

**Comment by robinwalas** [comment]
It's not only on iOS but also in my google chrome browser on my macbook. 
Didn't make any changes in the config file. 

That's one thing i can try, to comment out the header badges. I'm also redownloading layout-card.

**Comment by robinwalas** [comment]
Found the problem. 
There were 2 versions of layou-card on my system. 
One older one. After deleting the problem is solved. 
Thanks for the help!
