### ISSUE TITLE
How to make a new sensor for a group

### ISSUE THREAD

**Issue by fraserb2** [jimz011/homekit-infused#170]
I would like to split the lights currently on entity into a separate sensor for each floor of the house. I have added new groups in the device counter but I do not know how to make the final sensor for example (sensor.upstairs_lights_on, sensor.main_lights_on, etc). Is this done in the main home assistant setup or is there something in your setup that can facilitate adding these sensors

**Comment by jimz011** [comment]
The sensors are created by both a group and a sensor.

You need to create both. In HKI you can find examples, the group file used in HKI is called device_counters.yaml. The sensors are located in /packages/homekit-infused/hki_sensors.yaml

Take a look at both and I'm sure you might find a great example on how to recreate it.
