### ISSUE TITLE
Room shows as blank

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#171]
Hi, I am trying to figure out what I've done wrong here, I followed the "custom addon" tutorial to try and make the remote I made appear without a title at the top and it works in every single room, except this one.... Here is the code for the whole room, I am just trying to figure out why the entities/remote isn't showing and the room is blank. Thanks.

<img width="1117" alt="Screen Shot 2022-06-23 at 4 16 54 PM" src="https://user-images.githubusercontent.com/3034555/175392021-cc0f5935-29b9-4818-aff9-efcc3856d37c.png">

`
media_room:
    show_subtitle: false
    show_header: false
    title: Basement Google TV
    icon: mdi:television
    show_in_navbar: true
    show_in_menu: true
    panel: true

    custom:
      - cards:
          - type: "custom:vertical-layout"
            cards:
              - type: grid
                square: false
                columns: 1
                cards:
                  - type: conditional
                    conditions:
                      - entity: media_player.android_tv_192_168_2_123
                        state: "playing"
                      - entity: media_player.android_tv_192_168_2_123
                        state: "unavailable"
                      - entity: media_player.android_tv_192_168_2_123
                        state: "idle"
                    card:
                      type: "custom:mini-media-player"
                      entity: media_player.android_tv_192_168_2_123
                      name: Google TV
                      volume_stateless: false
                      artwork: full-cover
                      replace_mute: play_pause
                      info: scroll
                      group: false

              - type: grid
                columns: 4
                square: false
                cards:
                  - type: picture
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: >-
                          am start -n com.netflix.ninja/.MainActivity -a
                          android.intent.action.VIEW
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    hold_action:
                      action: none
                    image: https://www.svgrepo.com/show/354109/netflix-icon.svg
                    theme: Mushroom

                  - type: picture
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: >-
                          am start -n
                          com.disney.disneyplus/com.bamtechmedia.dominguez.main.MainActivity
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    hold_action:
                      action: none
                    image: >-
                      https://seeklogo.com/images/D/disney-logo-9649A88458-seeklogo.com.png
                    theme: Mushroom

                  - type: picture
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: "am start -a android.intent.action.VIEW -n   com.amazon.amazonvideo.livingroom/com.amazon.ignition.IgnitionActivity"
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    hold_action:
                      action: none
                    image: >-
                      https://cdn.wezift.com/assets/apps/amazon-prime-video/logo/_imgSingle/208890/512x512bb.png?mtime=20220129040734
                    theme: Mushroom

                  - type: picture
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: "am start -a android.intent.action.VIEW -n   com.google.android.youtube.tv/com.google.android.apps.youtube.tv.activity.ShellActivity"
                      target:
                        entity_id: media_player.android_tv_192_168_2_123
                    hold_action:
                      action: none
                    image: >-
                      https://static.wikia.nocookie.net/ipod/images/e/e7/YouTube_iOS_2019.png/revision/latest?cb=20200610180756
                    theme: Mushroom

              - type: grid
                square: false
                columns: 3
                cards:
                  - type: button
                    show_name: true
                    show_icon: true
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: POWER
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    icon: mdi:power
                    show_state: false
                    hold_action:
                      action: none
                    theme: Mushroom
                    icon_height: 35px

                  - type: button
                    show_name: true
                    show_icon: true
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: HOME
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    show_state: true
                    theme: Mushroom
                    icon: mdi:home
                    hold_action:
                      action: none
                    icon_height: 35px

                  - type: button
                    show_name: true
                    show_icon: true
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: MENU
                      target: {}
                    show_state: true
                    theme: Mushroom
                    hold_action:
                      action: none
                    icon: mdi:menu
                    icon_height: 35px

              - type: grid
                square: true
                columns: 3
                cards:
                  - type: button
                    show_name: false
                    show_icon: false
                    tap_action:
                      action: none
                    hold_action:
                      action: none
                    theme: Mushroom
                  - type: button
                    show_name: true
                    show_icon: true
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: UP
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    icon: mdi:arrow-up-bold-circle
                    show_state: true
                    hold_action:
                      action: none
                    theme: Mushroom
                    icon_height: 50px
                  - type: button
                    show_name: false
                    show_icon: false
                    tap_action:
                      action: none
                    theme: Mushroom
                    hold_action:
                      action: none

              - type: grid
                square: true
                columns: 3
                cards:
                  - type: button
                    show_name: true
                    show_icon: true
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: LEFT
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    icon: mdi:arrow-left-bold-circle
                    show_state: true
                    hold_action:
                      action: none
                    theme: Mushroom
                    icon_height: 50px
                  - type: button
                    show_name: false
                    show_icon: true
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: CENTER
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    hold_action:
                      action: none
                    icon: mdi:square-rounded-outline
                    show_state: false
                    theme: Mushroom
                    icon_height: 50px
                  - type: button
                    show_name: true
                    show_icon: true
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: RIGHT
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    icon: mdi:arrow-right-bold-circle
                    show_state: true
                    theme: Mushroom
                    hold_action:
                      action: none
                    icon_height: 50px

              - type: grid
                square: true
                columns: 3
                cards:
                  - type: button
                    show_name: false
                    show_icon: false
                    tap_action:
                      action: none
                    hold_action:
                      action: none
                    theme: Mushroom
                  - type: button
                    show_name: true
                    show_icon: true
                    tap_action:
                      action: call-service
                      service: androidtv.adb_command
                      service_data:
                        command: DOWN
                      target:
                        device_id: 98797e23ee63d4b9b0b4b7bedcb15958
                    show_state: true
                    theme: Mushroom
                    hold_action:
                      action: none
                    icon: mdi:arrow-down-bold-circle
                    icon_height: 50px
                  - type: button
                    show_name: false
                    show_icon: false
                    tap_action:
                      action: none
                    show_state: false
                    hold_action:
                      action: none
                    theme: Mushroom

`

**Comment by jimz011** [comment]
change this at the top:

```yaml
type: "custom:vertical-layout"
```
to
```yaml
type: vertical-stack
```

**Comment by dnestico** [comment]
Fixed it! Thanks again.

<img width="1109" alt="Screen Shot 2022-06-25 at 2 23 18 PM" src="https://user-images.githubusercontent.com/3034555/175785954-a49d261c-fc03-4c16-b707-9f3fa59ba693.png">
