### ISSUE TITLE
Can't remove dashboard

### ISSUE THREAD

**Issue by dalethomas** [jimz011/homekit-infused#172]
New to HA and trying to just remove the HomeKit Infused 5 dashboard.  How can I do that?

**Comment by jimz011** [comment]
Just remove the 3 folders (packages, hki-base and hki-user) and remove the packages line in configuration.yaml.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: dalethomas ***@***.***>
Sent: Saturday, June 25, 2022 1:59:24 PM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] Can't remove dashboard (Issue #172)


New to HA and trying to just remove the HomeKit Infused 5 dashboard. How can I do that?
