### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by williamxue80** [jimz011/homekit-infused#173]
How to change the background color from black to another? Choose the custom light, but the pious can't become white

**Comment by jimz011** [comment]
Make sure you set the settings from the yellow arrow first. Then with the red arrow you can select which theme to edit.

![Screenshot_20220707-023803_Home Assistant.jpg](https://user-images.githubusercontent.com/47046878/177833778-b12ddac8-3891-45ff-b993-6cc50b6bee93.jpg)

Lastly also make sure that in your profile you choose backend selected

![Screenshot_20220707-192741_Home Assistant.jpg](https://user-images.githubusercontent.com/47046878/177834107-7de9d2a5-ae57-4b83-99a5-90aa85685c72.jpg)

Lastly to change the background color (or image) you can select the active theme first (the active theme is either decided by time of day or by the system, on windows if you have dark mode enabled, the light mode will never show)

![Screenshot_20220707-192933_Home Assistant.jpg](https://user-images.githubusercontent.com/47046878/177834390-f94dcdc1-84c6-49aa-80c1-759fea5762f1.jpg)

**Comment by williamxue80** [comment]
Thank you，I mean how to change the color about this![image](https://user-images.githubusercontent.com/79845297/177922847-c71a7565-899f-4fc7-9eb9-5460156e05d3.png)

**Comment by williamxue80** [comment]
Sorry, I didn't describe it clearly.

**Comment by jimz011** [comment]
Currently this is not possible, sorry
