### ISSUE TITLE
Profile not opening pop-up

### ISSUE THREAD

**Issue by Roryan1993** [jimz011/homekit-infused#175]
Check the following:
1. Did you install all of the requirements?
2. Did you install config-template-card?
3. Did you install text-input-row?
4. Did you install fold-entity-row?
5. Did you install button-card?
6. Did you install card-mod?
7. Did you install browser-mod?
8. Are all of the above loaded in your resources?
9. Is your person entity the same name as the user?
10. Please check all of this and let me know if you got it to work.

I dit check everything of the above and I also checked the beta download for the button card. Also all the repo's are present.

Also my profile name is the same as my username.

Can you please help?

Right now the profile button doesnt pop up.

**Comment by jimz011** [comment]
Did you try an incognito browser window?
If it works there then clear your cache.

**Comment by jimz011** [comment]
After reading your comment again, make sure that your username and user have the same name. If not it will not open the popup.
