### ISSUE TITLE
thermostat problem

### ISSUE THREAD

**Issue by lujiashun1** [jimz011/homekit-infused#176]
![wenti](https://user-images.githubusercontent.com/6397951/186571565-0c986478-8e1d-4581-a8e3-26e6f192e6ac.png)
mode undifined ,how to debug and fix it?

**Comment by jimz011** [comment]
This is because your thermostat probably doesn't show the current `hvac_mode`, it will only show a state instead.

There is no good fix for it except the fix below:

Replace the following line in `/hki-base/templates/button/hki-thermostat.yaml` 

```yaml
# replace line 19 with:
state_display: "[[[ if (states['{{entity}}'].state == 'off') return `Off`; else return `${states['{{entity}}'].state}` ]]]"
```

Reload lovelace afterwards (you can reload lovelace by clicking on your profile photo in the top right and then scroll the navigation bar to the left). If you can't find it you can also just restart HA instead.

**Comment by lujiashun1** [comment]
> This is because your thermostat probably doesn't show the current `hvac_mode`, it will only show a state instead.
> 
> There is no good fix for it except the fix below:
> 
> Replace the following line in `/hki-base/templates/button/hki-thermostat.yaml`
> 
> ```yaml
> # replace line 19 with:
> state_display: "[[[ if (states['{{entity}}'].state == 'off') return `Off`; else return `${states['{{entity}}'].state}` ]]]"
> ```
> 
> Reload lovelace afterwards (you can reload lovelace by clicking on your profile photo in the top right and then scroll the navigation bar to the left). If you can't find it you can also just restart HA instead.

Thank you very much. it works.But there is another problem the popup-card does not display hvac_mode buttons. 
![f14e4a27866ec776508f18b8f09d4d5](https://user-images.githubusercontent.com/6397951/186834381-1a9a8384-7104-488a-a8b4-d112d957e7a5.jpg)
My climate entity attributes
![image](https://user-images.githubusercontent.com/6397951/186835654-f51343fe-ca85-43e6-9907-0654e0a7afe2.png)
modeIcons contains hvac_mode
![image](https://user-images.githubusercontent.com/6397951/186837192-d4014784-99a2-41ea-b044-4ca2f81f6fe6.png)
I tried to show the mode,but it did not work
![image](https://user-images.githubusercontent.com/6397951/186839862-bfaa9f60-5779-4408-96e2-35621929c300.png)

**Comment by jimz011** [comment]
I am not entirely sure, I did not create the popup card code. For this you better open an issue on the original creator's repository.

You can find the original creator in the docs (go to the button addon and click on the link).

**Comment by lujiashun1** [comment]
> I am not entirely sure, I did not create the popup card code. For this you better open an issue on the original creator's repository.
> 
> You can find the original creator in the docs (go to the button addon and click on the link).

OK  Thank you

**Comment by lujiashun1** [comment]
> I am not entirely sure, I did not create the popup card code. For this you better open an issue on the original creator's repository.
> 
> You can find the original creator in the docs (go to the button addon and click on the link).

It is OK now    Because I installed the wrong Lovelace
