### ISSUE TITLE
How to use device counters

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#177]
I added all my lights to the device_counters page thinking that would count with a number how many lights are on, but when I go to look at the states, there is no number so not sure how to be able to use this my templates and stuff since I wanted it to show me a number of how many lights are on.

**I'm on the latest version of HKI 4 still.**

<img width="244" alt="Screen Shot 2022-08-25 at 9 54 55 AM" src="https://user-images.githubusercontent.com/3034555/186683875-1755fa38-e277-4d8c-8832-10d7685f3932.png">

<img width="646" alt="Screen Shot 2022-08-25 at 9 55 25 AM" src="https://user-images.githubusercontent.com/3034555/186684004-61e79ad5-1691-4601-a55a-66f7167e9e80.png">

**Comment by jimz011** [comment]
Try using the sensors instead of the groups 😄 as described here:

https://github.com/jimz011/homekit-infused/blob/5.x.x-docs/docs/addons/device-counters.md

**Comment by dnestico** [comment]
Found it thanks!

**Comment by dnestico** [comment]
Found it thanks!
