### ISSUE TITLE
popup-card error after update v5

### ISSUE THREAD

**Issue by dworkin74** [jimz011/homekit-infused#178]
I have an missing popup-card error after updating to v5 with the notifications. What is wrong?

type: custom:popup-card
entity: input_boolean.dummy1
title: ' '
size: fullscreen
style: |
  --popup-background-color: black !important;
  --popup-header-background-color: var(--popup-background-color) !important;
card:
  type: vertical-stack
  cards:
    - type: conditional
      conditions:
        - entity: binary_sensor.latest_version_update_available
          state: true
      card:
        type: custom:button-card
        name: Er is een update voor Home Assistant!!
        icon: mdi:home-assistant
        entity: input_boolean.dummy1
        tap_action:
          action: more-info
          haptic: light
        hold_action:
          action: none
        styles:
          card:
            - height: 30px
            - width: 300px
            - '-

notification.yaml
- type: conditional
  conditions:
    - entity: sensor.version_updater
      state: "Update available"
  card:
    !include
    - '../hki-base/templates/header/subtitle-notification-template.yaml'
    - icon: mdi:home-assistant
      name: Er is een update voor Home Assistant!!

# Smoke Detector Triggered

- type: conditional
  conditions:
    - entity: binary_sensor.sd_gang_smoke_alarm_smoke_detected
      state: "on"
  card: 
    !include
    - "../hki-base/templates/header/subtitle-notification-template.yaml"
    - icon: mdi:smoke-detector
      name: Er is rook gesignaleerd in de gang!!
      spin: true

# Smoke Detector Triggered
- type: conditional
  conditions:
    - entity: binary_sensor.sd_overloop_1e_smoke_alarm_smoke_detected
      state: "on"
  card: 
    !include
    - "../hki-base/templates/header/subtitle-notification-template.yaml"
    - icon: mdi:smoke-detector
      name: Er is rook gesignaleerd op de 1 etage!!
      spin: true

# Smoke Detector Triggered
- type: conditional
  conditions:
    - entity: binary_sensor.sd_overloop_2e_smoke_alarm_smoke_detected
      state: "on"
  card: 
    !include
    - "../hki-base/templates/header/subtitle-notification-template.yaml"
    - icon: mdi:smoke-detector
      name: Er is rook gesignaleerd op de 2 etage!!
      spin: true

# Smoke Detector Triggered
- type: conditional
  conditions:
    - entity: binary_sensor.sd_woonkamer_smoke_alarm_smoke_detected
      state: "on"
  card: 
    !include
    - "../hki-base/templates/header/subtitle-notification-template.yaml"
    - icon: mdi:smoke-detector
      name: Er is rook gesignaleerd in de woonkamer!!
      spin: true

# voordeur_contact
- type: conditional
  conditions:
    - entity: binary_sensor.voordeur_contact
      state: "on"
  card: 
    !include
    - "../hki-base/templates/header/subtitle-notification-template.yaml"
    - icon: mdi:door
      name: De voordeur staat open!

# Woonkamer Deur
- type: conditional
  conditions:
    - entity: binary_sensor.achterdeur_contact
      state: "on"
  card: 
    !include
    - "../hki-base/templates/header/subtitle-notification-template.yaml"
    - icon: mdi:door
      name: De achterdeur staat open!

# Studeerkamer Deur
- type: conditional
  conditions:
    - entity: binary_sensor.studeerkamer_deur_contact
      state: "on"
  card: 
    !include
    - "../hki-base/templates/header/subtitle-notification-template.yaml"
    - icon: mdi:door
      name: De studeerkamer deur staat open!

**Comment by jimz011** [comment]
Could you show the error and post a screenshot? 

Also I'd love it if you'd use code blocks when pasting code.

```yaml
this:
  is way more readable
to: me
```

**Comment by dworkin74** [comment]
![12353D00-8C15-44E2-93BB-C9CD9D5EBDA1](https://user-images.githubusercontent.com/6012874/188794704-360d02d4-5bd6-4d39-8859-a0688de4cd35.jpeg)

This is a screenshot of the error.

**Comment by fstelte** [comment]
I am having the same issue after updating to V5. Seems it is related to the notifications that can be created with HKI

**Comment by jimz011** [comment]
Yes and no,

Go to settings>integrations and devices and check if browser mod is loaded. It is an integration now.

The error should disappear once browser mod is loaded (you can check the version by pressing f12 in your browser and going to the console).

The error should be gone, though the code is a bit messed up since the last update. This will be fixed tonight.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fstelte** [comment]
I noticed that the integration was giving this error:

 Migration handler not found for entry Browser Mod for browser_mod 

Removed the integration, re-installed it. Restarted Home Assistant. Problem is gone now

**Comment by dworkin74** [comment]
This resolved it for me as well.

> I noticed that the integration was giving this error:
> 
> Migration handler not found for entry Browser Mod for browser_mod
> 
> Removed the integration, re-installed it. Restarted Home Assistant. Problem is gone now

**Comment by jimz011** [comment]
Update incoming tonight, it removes some unnecessary code that got introduced with the last update. It doesn't solve this issue directly, since well browser_mod needs to be loaded correctly (as you guys have encountered). But at least users that still need updating won't face this error, they'll still see errors, but at least their dashboard stays somewhat functional).

Closing this issue now since well, issue was resolved 😄
