### ISSUE TITLE
[FR] Add a Basement/Garage floor

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#18]
Adding a basement or a garage floor would allow for better group organization.

Thanks for the consideration!

**Comment by jimz011** [comment]
I will look into this, however I might revise the groups within the upcoming week. So I keep it on hold for a while.

**Comment by jimz011** [comment]
Added in beta8 closing this issue now!

**Comment by jimz011** [comment]
This issue was closed in the past, however I did want to add a mention to this.

You can have infinite rooms in HKI 3.0.0! The code has also shrunk from a few 1000 lines to a mere 100.

Enjoy!
