### ISSUE TITLE
Issue with popup-card

### ISSUE THREAD

**Issue by gogostoro** [jimz011/homekit-infused#180]
Hi and apologies if it's stupid question as i'm noob at coding maybe i missed obvious...

I followed (tried) installation guide and now i'm getting following error. 

![image](https://user-images.githubusercontent.com/73707479/189970918-3b7b1c9a-227c-46b5-86e9-5b5ebd7e7f4a.png)

I have checked and i installed all of integrations and frontends from your list, but don't know what i missed. 
Any advice would help. 

Thx!

**Comment by jimz011** [comment]
https://community.home-assistant.io/t/homekit-infused-5-hki-v2022-5-1-september-hotfixes/117086/1567?u=jimz011

And

https://community.home-assistant.io/t/homekit-infused-5-hki-v2022-5-1-september-hotfixes/117086/1570?u=jimz011

**Comment by jimz011** [comment]
The mentioned links should have fixed this problem for you, if not make sure to clear cache!

Closing this now!
