### ISSUE TITLE
Use of packages

### ISSUE THREAD

**Issue by RolandWijnen** [jimz011/homekit-infused#181]
I've installed everything according to the documentation. Just one question about how to use packages. 

I already use packages to include all the integrations following the 'separation of concerns' setup as suggested by [Frenck](https://github.com/frenck/home-assistant-config/blob/master/configuration.yaml): 

`  packages: !include_dir_named integrations`

How should I combine this with the packages setup for Homekit infused?

`  packages: !include_dir_named packages/`

Thanks for your help!

**Comment by jimz011** [comment]
Just rename your `integrations` folder to `packages` and then paste the folders in there, that should suffice (not sure how Frenck splits his config, but I think it should work).

Make sure you replace this `packages: !include_dir_named integrations` into this `packages: !include_dir_named packages`

**Comment by RolandWijnen** [comment]
Thanks a lot Jimmy! It's working!
