### ISSUE TITLE
Custom element doesn't exist: popup-card.

### ISSUE THREAD

**Issue by Oropezaj** [jimz011/homekit-infused#183]
Hi, I am new in home assistant and I tried to install the homekit infused following the video and instructions. But I have an error (Custom element doesn't exist: popup-card.) and I can't find how to fix it. Also, on the hki_automations.yaml show two incorrect type on the (initial_state:). Any idea of what is wrong and how to fix it?

automation:     
# Theme Selector
  - alias: 'themes'
    initial_state: 'true' Incorrect type. Expected "boolean".
    trigger:
      - platform: state
        entity_id: input_select.theme_selector_dark
      - platform: state
        entity_id: input_select.theme_selector_light
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
    action:
      - service: frontend.set_theme
        data_template:
          name: >
            {% if is_state('sun.sun', 'below_horizon') %}
              {{ states('input_select.theme_selector_dark') }}
            {% else %}
              {{ states('input_select.theme_selector_light') }}
            {% endif %}
          mode: >
            {% if is_state('sun.sun', 'below_horizon') %}
              dark
            {% else %}
              light
            {% endif %}
  - alias: 'theme editor'
    initial_state: 'true' Incorrect type. Expected "boolean".
    trigger:
      - platform: state
        entity_id: sun.sun

**Comment by Oropezaj** [comment]
I found the solution in another issue log.

**Comment by Deathleaves** [comment]
> 
I have the same issue. How did you solve this?
