### ISSUE TITLE
Button label shows uppercase letter even though its not set like that

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#184]
button_label: "[[[ if (states['sensor.current_covers_open'].state == 0) return `Alle screens er lukket`; if (states['sensor.current_covers_open'].state == 1) return `1 Screen er åpen`; else return `${states['sensor.current_covers_open'].state} Screens er åpen`; ]]]"
    
   AFter updating to 5.1 my homescreen suddenly shows like this 
   
   Why is the text Uppercase after each space "X Screens er åpen" turns into "X Screens Er Åpen"

![image](https://user-images.githubusercontent.com/6884716/195456259-c236f6db-b424-4827-b0d7-db214af14a00.png)

**Comment by jimz011** [comment]
I will add this to the todo list for the next update so that you can change this.

**Comment by jimz011** [comment]
This is addressed in the upcoming version, closing this now
