### ISSUE TITLE
Invalid configuration for grid

### ISSUE THREAD

**Issue by alligator999** [jimz011/homekit-infused#187]
Hi,

I`m after fresh install. On views there are error messages. Is some resource missing , how I can tell which one?

![image](https://user-images.githubusercontent.com/35902744/199323376-509607f8-1a41-48e4-8caa-5b4ef71f805a.png)

Regards,
RD

**Comment by jimz011** [comment]
No,, no resources are missing, you just don't have any card configured on that view yet.
Configure an addon or custom card and report if it works for you.

**Comment by alligator999** [comment]
Yes it does !!. Thanks for help :)
