### ISSUE TITLE
Thermostat addon not displaying thermostat

### ISSUE THREAD

**Issue by 602293544** [jimz011/homekit-infused#188]
[Homekit Infused 5 (2022.5.1)](https://github.com/jimz011/homekit-infused/releases/tag/2022.5.1)

![1](https://user-images.githubusercontent.com/54359412/199730830-8e6904da-0ddb-455f-afa6-80ac192db6ea.png)
![2](https://user-images.githubusercontent.com/54359412/199730855-c724f7c3-91d2-4cee-8a78-71433bceb3e4.png)
![3](https://user-images.githubusercontent.com/54359412/199730864-2eaa8fd8-6dc2-452d-bc42-4151ea13f622.png)
![4](https://user-images.githubusercontent.com/54359412/199730872-4c0359a5-5171-491d-a861-b9aca7d9609d.png)

**Comment by jimz011** [comment]
If you mean it is not showing a thermostat, then this is correct, in your code it will only render if the screen width is max 350px.

Either remove the view layout part or change `max` into `min` (what it does is showing cards depending on screen size)

**Comment by 602293544** [comment]
Thank you very much
