### ISSUE TITLE
New install (on top of 3+ year install) but Pop-ups in top right not working

### ISSUE THREAD

**Issue by itsaints** [jimz011/homekit-infused#189]
Installed the homekit and checked: -

- Browser Mod installed and register slide button turned on
- Button card confirmed as running version 3.5.0-dev.1 from console tab in F12 dev tools (taken from your repo)
- Nothing added to base config except some notification's entities and device counters so far
- Profile button fills whole screen 
- All other top right buttons fill whole screen with nothing in them so none of the defined entities are coming through either (as per bug discussed with button card fix)
- Double checked resources and all look to be defined

Watched all the youtube vidoes, what can I check next ?

Thanks.

J.

**Comment by jimz011** [comment]
Could you share a screenshot of those popups and profile menu?

**Comment by itsaints** [comment]
![image](https://user-images.githubusercontent.com/51716227/199966726-5fffd1b9-d205-4020-86bd-0a785b8eb371.png)

![image](https://user-images.githubusercontent.com/51716227/199966795-5f851de3-dd5b-41ec-9aa3-fea300b6b7a8.png)

**Comment by jimz011** [comment]
The profile menu is working correctly, you will need to fill it with whatever you want. It is fullscreen because otherwise it looks horrible on a phone, but you can change this in hki-user/config/config.yaml as described in the docs.

I also see you are running HA 2022.11.x, unfortunately HKI is not yet fully compatible with that. It will work fine, though it has some ugly lines that need to be addressed (I will push the update this weekend).

As for the device counters is it a completely new install (as in you do not have entities yet) or did you install all entities you have? If the latter is true share the device_counters.yaml file

**Comment by itsaints** [comment]
Not added everything but some to see what it would look like:-

# Homekit Infused Device Counters

# Fill this file to have the badges and device counters work in HKI.
# You can use these sensors in your badges.


# All Radiator Valves or Climate entities (ONLY climate entities can be used here!, if you have a single thermostat put it here as well)
all_climate_entities:
  entities:
    - climate.family_room
    - climate.joe_s_room
    - climate.living_room
    - climate.main_bedroom
    - climate.sam_s_room

# All Fans (Enter all your fans in here)
all_fan_entities:
  entities:

# Window Sensors (This is used in the header badges, without this the header badge won't work)
all_window_sensor_entities:
  entities:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_0081c507_on_off
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off

# Door Sensors (This is used in the header badges, without this the header badge won't work)
all_door_sensor_entities:
  entities:

# Motion Sensors (This is used in the header badges, without this the header badge won't work)
all_motion_sensor_entities:
  entities:
    - binary_sensor.30_merchiston_mews_family_room_motion
    - binary_sensor.30_merchiston_mews_joes_room_motion
    - binary_sensor.30_merchiston_mews_living_room_motion
    - binary_sensor.30_merchiston_mews_master_br_motion
    - binary_sensor.30_merchiston_mews_sams_room_motion
    - binary_sensor.back_garden_motion
    - binary_sensor.front_garden_motion
    - binary_sensor.gate_motion
    - binary_sensor.hue_motion_sensor_1_motion
    - binary_sensor.living_room_sensor_motion

# All Detectors (smoke/gas/fire etc)
all_detector_entities:
  entities:
    - binary_sensor.30_merchiston_mews_hallway_smoke
    - binary_sensor.30_merchiston_mews_master_br_smoke
    - binary_sensor.30_merchiston_mews_joe_s_room_smoke
    - binary_sensor.30_merchiston_mews_sam_s_room_smoke

# All Binary Sensors (put all your binary sensors here e.g. smoke/gas/fire/door/window/motion etc. You can use this as a counter on the security button)
all_binary_sensor_entities:
  entities:
    
# All Lights
all_light_entities:
  entities:
    - light.livingroom_light_1
    - light.livingroom_light_2
    - light.livingroom_light_4
    - light.livingroom_light_3

# All Devices
all_device_switch_entities:
  entities:
    
# All Covers
all_cover_entities:
  entities:

# All Garage Doors
all_garage_door_entities:
  entities:

# All Entities # Put ALL of the above entities in here to get the most out of HKI on mobile phones
all_entities:
  entities:
    - climate.family_room
    - climate.joe_s_room
    - climate.living_room
    - climate.main_bedroom
    - climate.sam_s_room

    - binary_sensor.lumi_lumi_sensor_magnet_aq2_0081c507_on_off
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off

    - binary_sensor.30_merchiston_mews_family_room_motion
    - binary_sensor.30_merchiston_mews_joes_room_motion
    - binary_sensor.30_merchiston_mews_living_room_motion
    - binary_sensor.30_merchiston_mews_master_br_motion
    - binary_sensor.30_merchiston_mews_sams_room_motion
    - binary_sensor.back_garden_motion
    - binary_sensor.front_garden_motion
    - binary_sensor.gate_motion
    - binary_sensor.hue_motion_sensor_1_motion
    - binary_sensor.living_room_sensor_motion

    - binary_sensor.30_merchiston_mews_hallway_smoke
    - binary_sensor.30_merchiston_mews_master_br_smoke
    - binary_sensor.30_merchiston_mews_joe_s_room_smoke
    - binary_sensor.30_merchiston_mews_sam_s_room_smoke

    - light.livingroom_light_1
    - light.livingroom_light_2
    - light.livingroom_light_4
    - light.livingroom_light_3

**Comment by jimz011** [comment]
That looks fine to me. So if you turn on a light it will not show a badge number?

**Comment by itsaints** [comment]
Sorry I assumed they would appear even if not on when I clicked on the badges and because the pop-up looked wrong I just went looking for errors. All working and I'll review the setting for changing the full screen look.

Great work by the way :-)

Thanks for the super-fast support.

J.
