### ISSUE TITLE
HKI giving error while loading after adding plant status in view

### ISSUE THREAD

**Issue by robinwalas** [jimz011/homekit-infused#194]
When adding plant status addon in a view and after restarting i've got an unsuspected error in lovelace.
After searching for a while i've discovered an error in "hki-base/base.yaml" 

Line 269 --> "- addons/media-player.yaml" has to be "- addons/plant-status.yaml"

                      # Plant Status // *Can be removed
                      {% if 'plant_status' in addon %}
                      - !include 
                        - addons/media-player.yaml
                        - config: {{ config|tojson }}
                      {% endif %}

![Schermafbeelding 2022-11-13 om 19 04 11](https://user-images.githubusercontent.com/70822027/201537121-276bcab4-ac3b-48f8-ab40-fc369b09909e.png)

**Comment by jimz011** [comment]
Thanks for the find, I will fix it

**Comment by robinwalas** [comment]
No problem! I had discovered this already a while ago, but forgot to report. 
Now after updating to the newest version, i've got this error again, and after searching i had found the solution again.

**Comment by jimz011** [comment]
This has been fixed in the last update.
