### ISSUE TITLE
Custom element doesn't exist: popup-card

### ISSUE THREAD

**Issue by Deathleaves** [jimz011/homekit-infused#199]
I have encountered an issue "custom element doesn't exist" which is shown in every View.  I am installing HKI (2022.6.3) on a clean Home Assistant (2022.12.8) exactly following the Document and Video. I can not find what causes this error. Can someone help me? Really appreciate.

Custom element doesn't exist: popup-card.
type: custom:popup-card
entity: input_boolean.dummy1
title: ' '
size: fullscreen
style: |
  --popup-background-color: black !important;
  --popup-header-background-color: var(--popup-background-color) !important;

  --popup-border-radius: 28px !important;
   
card:
  type: vertical-stack
  cards:
    - type: conditional
      conditions:
        - entity: input_boolean.dummy1
          state_not: dummy
      card:
        type: custom:button-card
        name: No notifications yet, please open /hki-user/notifications.yaml
        icon: mdi:alert
        entity: input_boolean.dummy1
        tap_action:
          action: more-info
          haptic: light
        hold_action:
          action: none
        styles:
          card:
            - height: 30px
            - width: 300px
            - '--ha-card-background': transparent
            - box-shadow: none
            - overflow: visible
            - border-style: none
          name:
            - justify-self: start
            - font-family: var(--font-family)
            - color: var(--subtitle-text-color)
            - font-size: var(--subtitle-font-size)
            - font-weight: var(--subtitle-font-weight)
            - padding-left: 10px
            - margin-top: '-12px'
            - overflow: visible
          img_cell:
            - height: 45px
            - width: 45px
            - position: absolute
            - top: '-6px'
            - left: 0px
            - overflow: visible
          icon:
            - overflow: visible
            - color: var(--subtitle-text-color)
          grid:
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
        state:
          - operator: '0'
            spin: false
          - value: 'off'
            spin: false

**Comment by Deathleaves** [comment]
![image](https://user-images.githubusercontent.com/36256719/210194066-6996a1b6-7874-4f97-9b47-39aaab9fcde2.png)
And the Counters on the up-right are not working (click and no responding)

**Comment by Deathleaves** [comment]
Found the solution in your homepage. Thanks.

**Comment by Berndxyz** [comment]
Please tell me the solution !!
Thanks a lot

**Comment by Berndxyz** [comment]
> Found the solution in your homepage. Thanks.
 Please tell me the solution ! Thanks a lot !!
