### ISSUE TITLE
After first time installation - Error - "Custom element doesn´t exist: popup-card."

### ISSUE THREAD

**Issue by Sup3rMario** [jimz011/homekit-infused#207]
Hi,
i was interessted on your dashboard, so i installed all from your Video Part 1. But after Restart (3 times) i had errors - see sreen-shot
what was wrong?
Thanks for help,
Mario
![ScreenShot 20230409-134038](https://user-images.githubusercontent.com/10222176/230770716-90fe13fd-c44a-4d24-a11b-9c8078eb04da.PNG)
the only thing i found (i am a newbie) is, that the popup-card is deprecated and use now browser_mod.

**Comment by jimz011** [comment]
Please check out the issues section of the documentation as the solution is found there.

**Comment by Sup3rMario** [comment]
Thanks a lot, the browser_mod was not loaded.
