### ISSUE TITLE
Package hki_configuration setup failed. Component lovelace has duplicate key 'mode'

### ISSUE THREAD

**Issue by Epimedium** [jimz011/homekit-infused#210]
Hi,
Today I wanted to install home kit infused. After following all steps I got this when testing the yaml files before a restart:

"Package hki_configuration setup failed. Component lovelace has duplicate key 'mode'"

When I remove "homeassistant:  packages: !include_dir_named packages/" from the configuration.yaml file then the message disappears and a restart is possible. But then of course homekit infused won't start.

I installed version 2023.1.2

Any thoughts? 
Thanks, Erik

**Comment by jimz011** [comment]
Hi Erik,

You probably have this in your configuration.yaml file

```yaml
lovelace:
  mode: storage
```

by removing the mode line it will probably fix the issue you have.

**Comment by Epimedium** [comment]
It works now thanks!
