### ISSUE TITLE
[FR] input_select for day & night themes

### ISSUE THREAD

**Issue by tbrasser** [jimz011/homekit-infused#23]
It would be cool to choose 2 themes, one dark and one light theme, and then be able to have them on auto (day/night) or 'manual'.

This way we can choose the 'auto' themes ourselves.

**Comment by jimz011** [comment]
Cool idea, not entirely sure if it is possible, but I like the idea. I will sit on this. Thanks for the suggestion!

**Comment by jimz011** [comment]
Actually, been thinking a bit more on it, I think this can be done without much effort. If I succeed you can expect this feature to arrive soon!

**Comment by jimz011** [comment]
Added in beta 7, closed!
