### ISSUE TITLE
[ISSUE] HKI About --> Updates link not working

### ISSUE THREAD

**Issue by tbrasser** [jimz011/homekit-infused#24]
It links to https://jimz011.github.io/homeassistant which returns an 404.

Also, even though I run 2.0b6, it shows as if there is an update available. 

kutgw!

**Comment by jimz011** [comment]
Fixed in beta 7, was a known issue. The repo has been renamed from homeassistant to homekit-infused to better reflect that is is not my personal setup!

Beta7 soon!
