### ISSUE TITLE
[FR] Electricity use

### ISSUE THREAD

**Issue by abeksis** [jimz011/homekit-infused#25]
I would love for you to add electricity use

**Comment by jimz011** [comment]
Noted, will be added in a future release!

**Comment by lyazide** [comment]
I have a basic page for the linky if you would like.

**Comment by abeksis** [comment]
> I have a basic page for the linky if you would like.
Yes, that would be wonderful

**Comment by jimz011** [comment]
This will not be released, I will however put tutorials on the repo on how to create one in the future.
