### ISSUE TITLE
[ISSUE] Alarm Panel: Disable Button

### ISSUE THREAD

**Issue by pex81** [jimz011/homekit-infused#28]
**Describe the bug**
The DISABLE button does not appear in the alarm panel

**To Reproduce**
1. Go to 'Alarm Panel'
2. Click on 'Arm Away'

**Expected behavior**
When activated, the alarm of the alarm user content exits the deactivate button

Only if I update the page does the button appear.

**Screenshots**
![Immagine](https://user-images.githubusercontent.com/58252398/76679558-dd1e0300-65e1-11ea-8f22-85ac0d2a858e.png)

 
**Current Running Home Assistant version:**
HA 0.106.6

**Device HA running on and client device viewing lovelace:**
Virtual Machine Proxmox

**Additional context**
Thanks, great job!

**Comment by jimz011** [comment]
The keypad will be removed in beta 8 in favor of a much easier solution!
