### ISSUE TITLE
[FR] Add a confirmation popup to the Restart Home Assistant button

### ISSUE THREAD

**Issue by noodlemctwoodle** [jimz011/homekit-infused#29]
**Is your feature request related to a problem? Please describe.**
Please add a confirmation popup to the restart Home Assistant button in HA Settings? Sometimes I click without thinkng and then have to wait for Home Assistant to reboot.

**Describe the solution you'd like**
A confirmation to restart Home Assistant, like there is on the default instance and in HACs.

**Comment by jimz011** [comment]
Will add this in beta 8

**Comment by jimz011** [comment]
Fixed in beta 8, also fixed the automations reload not working!
