### ISSUE TITLE
Please can you make this installable as a HACS Theme?

### ISSUE THREAD

**Issue by MikeMannox** [jimz011/homekit-infused#32]
Easy of use. There are too many variables / parameters that need setting up to be able to enjoy this theme with the risk of breaking things. Especially for users not used to using this.

Ideally a one-click install via HACS.

There are other Themes which are similar, however they are not as full featured and require as much work to apply.
It'd be great if a dialogue could be created with other Home-Assistant UI developers, to discuss Lovelace layout alternatives or additional / simpler ways of theming. 
Whilst Lovelace utilizes Material Design and can be themed quite nicely, it does look a bit samey.

**Comment by jimz011** [comment]
I'd love to do this, but the amount of variables users need to do themselves are too great to handle in a generalized package. I might consider this in the future, but for now priorities lies in performance, stability and the finishing touches.
