### ISSUE TITLE
[ISSUE] jinja2.exceptions.UndefinedError 2.0.0 beta 7

### ISSUE THREAD

**Issue by rhayun** [jimz011/homekit-infused#33]
**Describe the bug**
`  File "/config/lovelace/views/01.menu.yaml", line 24, in top-level template code
    - name: "{{ _global.header_secondary.menu|default('return `Set your own template in YAML`') }}"
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'header_secondary'`

**Current Running Home Assistant version:**
0.108.9

**Device HA running on and client device viewing lovelace:**
PC

**Additional context**
No matter what i tried this is the error i got - its seems like the _global is empty

**Comment by jimz011** [comment]
This is a lovelace gen error and it seems that you are either missing the `user_content/extra_settings.yaml` file or that the lines within that file are commented out/removed. Make sure you have that file and lovelace_gen installed.

**Comment by rhayun** [comment]
yes i have this file and its included in: packages/homekit_infused/configuration.yaml

`lovelace_gen: !include ../../user_content/extra_settings.yaml`

**Comment by jimz011** [comment]
Did you also make sure that you have installed lovelace_gen (the custom_component) also check the extra_settings.yaml file and look for the header: attributes. Are they there? If not then the file will most likely not work and you will have to wait for beta8

Ah yes well I see you are running an unsupported version of Home Assistant.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by rhayun** [comment]
oh.. ok - thanks
when do you think beta 8 with 0.108.9 supported?

**Comment by jimz011** [comment]
It will be soon, and it will support all current versions of HA from 0.107.x to 0.109.x



Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by rhayun** [comment]
thanks t will be great
can you tell me whats the latest version of HA that it supported now?

**Comment by jimz011** [comment]
The latest version supported by HKI is home assistan 0.106.6. The changes made to the way dashboards and resources are handled had me needing to rewrite a large part of it. It also isn't perfect (hence the beta tag).

Just keep an eye on the repo (or join our discord server) to get notified as soon as it is released.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by rhayun** [comment]
Thank you - you are doing a wonderful job.. i will

**Comment by jimz011** [comment]
Beta 10 has been released (when updating from beta 7, please read the notes from beta 8 before you continue!

Please let me know if this has fixed your problems. For now I will close this issue. If this still persists, please create a new issue!
