### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by Nicxe** [jimz011/homekit-infused#37]
Not 100% sure this have anything to do with HKI 2.0, but it started when I installed HKI, it comes often. 546 times since this morning.

```
Log Details (ERROR)
Logger: frontend.js.latest.202004272
Source: components/system_log/__init__.py:209
First occurred: 7:36:30 AM (546 occurrences)
Last logged: 12:12:07 PM

:0:0 Script error.
http://192.168.156.2:8123/frontend_latest/chunk.9cedb8f1a54a4b78de8b.js:1441:255421 TypeError: null is not an object (evaluating 'e.parentElement.replaceChild')
https://iq1myt3k700o3e.ui.nabu.casa/frontend_latest/chunk.9cedb8f1a58de8b.js:1441:318 Uncaught TypeError: Cannot read property 'replaceChild' of null
```

**To Reproduce**
Error shows when I reload rescoursec from frontend

**Current Running Home Assistant version:**
0.109.3

**Device HA running on and client device viewing lovelace:**
Intel NUC and iPhone 8 Plus

**Comment by jimz011** [comment]
This has to do with Custom Header, I have already raised an issue with the author of this component. I hope we'll find a solution soon.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by jimz011** [comment]
This should have been fixed with the custom_header update (make sure you have the latest public release 1.4.7, do not get the 1.4.8 or 1.4.9 beta versions as they do not work!)
