### ISSUE TITLE
[FR] Show unit of measurement in button badge sensor

### ISSUE THREAD

**Issue by tbrasser** [jimz011/homekit-infused#38]
**Is your feature request related to a problem? Please describe.**
The sensors on the buttons show the value, but not the unit of measurement.

**Describe the solution you'd like**
I'd like to show the unit of measurement next to the vaule.

**Describe alternatives you've considered**
I can make template sensors which cast the value from a number to a string and add the unit in the string as well. But that would mean yet another bunch of (almost duplicate) sensors.

**Additional context**
n.a.

**Comment by jimz011** [comment]
Unfortunately in doing so I would have to complicate the setup quite a bit (which is not a nice result for the enduser). The other way I could do it is to hardcode it, though that would mean that on a button with a Celsius sign, putting any other sensor there will also show the Celsius sign.

For now I will suggest creating a template sensor (I know it would create yet another sensor, though I don't imagine people running template sensors for each button within HKI, though I might be wrong XD).

I will look into this, however I can not make any promises. I could make it that it is handled by the UI, but that would mean I'd need to create even more input_texts to compensate for that. The alternative is to have the possibility to completely template it (though I have tested this before, I am not sure if this actually worked or not). But by doing so, the easyness of the setup (which would be, just enter your entity and have it shown as a badge) would go to a much harder variant in which you have to enter complete templates like ``` "[[[ return if else etc ]]]```. This is possible like I said, but would make such a simple action as it is now a lot harder, as the button will not show when there are errors. A single error will make the button disappear and be useless. Finding these kind of errors can also be very hard to troubleshoot for the end user.

Though, if you really wanted to you could open the respective views and add a Celsius sign (or whatever sign) to that page. (If I'm correct you can go to /homekit-infused/templates/frontpage_buttons.yaml and /homekit-infused/includes/menu_all_buttons.yaml)

Just note that these files will be overwritten after an update. Though if you can live with changing the sign every 2 to 4 weeks you'll be fine.

**Comment by tbrasser** [comment]
allright, that's reasonable, I'll make template sensors for all badges. this way they also make sense for advanced headers.

**Comment by jimz011** [comment]
in the advanced header you can simply use templates (like shown in the example file `extra_settings.yaml`). No need for template sensors there. You'd only need template sensors for the button badges.
