### ISSUE TITLE
[ISSUE] Not possible to have fewer Garbage sensors than 4

### ISSUE THREAD

**Issue by tbrasser** [jimz011/homekit-infused#39]
**Describe the bug**
I have 4 garbage sensors, however, 2 of them are always on the same day, so I need only 3 of them in total. 
When I don't fill in the 4th one, lovelace screams :)

**To Reproduce**
1. Go to 'hki-settings --> garbage config'
2. Click on 'fill in all sensors except for the last one.'
3. Go back to 'home'

**Expected behavior**
It would be nice if it only shows the sensors that you have configured.

**Screenshots**

**Current Running Home Assistant version:**
e.g. 0.110.4

**Device HA running on and client device viewing lovelace:**
some x86 i7 machine on kubernetes (docker container)
clients: chromium, firefox and chrome mobile

**Additional context**
Already talked to you on discord. I have manually editted the frontpage.yaml files for now, although that's not working entirely smooth all of the time. (for some reason the hki-settings version of the frontpage keeps trying to load the 4th sensor, even though i have removed it from that yaml file. probably a caching error.

**Comment by jimz011** [comment]
I will work on this for the upcoming release. Expect it to have the same kind of behavior as the sensors inside the frontpage pictures do. I'll leave this open so I can track it.

**Comment by jimz011** [comment]
I will close this as this is fixed for the next release. Also note since you use (or have used a rpi) that the next update will be rpi compatible, light and super fast again.
