### ISSUE TITLE
[FR] Simple Weather Card - User assignable temperature sensor

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#40]
**Is your feature request related to a problem? Please describe.**
I have a home weather station that I would like to use with the Simple Weather Card on the home screen of HKI.

**Describe the solution you'd like**
I would love to see the card option of `custom` be floated in the UI or even in user_content so that I could add my own temperature sensor to Simple Weather Card.

**Describe alternatives you've considered**
I have considered modifying your template, but I am trying to keep as close to stock as possible so that I have an easier time updating.

**Additional context**
`# lovelace_gen`

`# card`
`type: custom:simple-weather-card`
`{% raw %}`
`style: |`
`  ha-card {`
`    border-radius: {{ states('input_select.border_radius_selector') }};`
`    var(--box-shadow)`
`    opacity: 0.8;`
`    font-size: 12px;`
`   font-family: Helvetica;`
`  }`
`{% endraw %}`
`entity: {{ entity|default('weather.dark_sky') }}`
`name: {{ city_name|default('Eindhoven') }}`
`backdrop: false`
`tap_action:`
`  action: navigate`
`  navigation_path: /hki/weather`
**`custom:`**
**`  - temp: {{ (user_temp_sensor) }}`**
^ That would be all that would be necessary to add to the file, and if other people don't fill it out, then it doesn't use that sensor to populate the temperature.

**Comment by jimz011** [comment]
I will take a look into this (and what it actually does). Could you maybe provide a screenshot to show me what the result would be like? If you can't post your screenshot here you may use discord instead.

**Comment by jimz011** [comment]
I am still looking at this (and I am sorry for the long time of hiatus), I will see what I can do however this has a somewhat low priority.

**Comment by MagicMountainMan** [comment]
This is now taken care of since the weather-card yaml is now exposed to the user via the add-on.

**Comment by jimz011** [comment]
I will close this then
