### ISSUE TITLE
[FR] Add input_boolean.(user_views) to all views

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#41]
**Is your feature request related to a problem? Please describe.**
Currently the Lights and Devices views do not have a way to activate the user_content from the frontend UI.

**Describe the solution you'd like**
It would be awesome if all user_content generated could be exposed on Lovelace via the UI.

**Describe alternatives you've considered**
I just added my own lines of yaml to enable the user_content on those views.

**Comment by jimz011** [comment]
The setup is going to change into yaml and will have user_content views on all views and enabled by default (without the need of edit mode)

**Comment by jimz011** [comment]
Closed
