### ISSUE TITLE
Brightness slider to tall on iPhone 7

### ISSUE THREAD

**Issue by giuliandenicola1** [jimz011/homekit-infused#42]
**Describe the bug**
The brightness slider from the lights are too tall on iPhone 7 (not tested on other devices)

**To Reproduce**
1. Go get an iPhone 7 (or older maybe)
2. Doube tap on lights button

**Expected behavior**
A slider that isn't too tall

**Screenshots**
![IMG-20200706-WA0006](https://user-images.githubusercontent.com/67443916/86765714-d2ccbc80-c049-11ea-99cf-b3fd1e049b41.jpg)

**Current Running Home Assistant version:**
0.112.2

**Comment by jimz011** [comment]
I am working on this to make it adjustable for smaller phones, you can expect this in the next update!

**Comment by jimz011** [comment]
Is this still an issue? If yes I will add a fix for it for v3.0.5.

**Comment by giuliandenicola1** [comment]
Now it looks like this [https://streamable.com/tflvw3](https://streamable.com/tflvw3)

**Comment by jimz011** [comment]
Hm that doesn't look very good :P, I just took a look on my wifes iPhone Xs, but that doesn't seem to exhibit this problem. Could you restate which phone you are using? I think it has to do something with the slider height, I will make this adjustable in the v3.0.5!

**Comment by giuliandenicola1** [comment]
It's a iPhone 7 the iPhone 11 doesn't have this issue.

**Comment by jimz011** [comment]
This issue is resolved in HKI 3.0.5, please refer to the button or auto fill addon documentation on how to change the slider/switch height.

The update will be released in a few hours,

Cheers!
