### ISSUE TITLE
[FR] Weather Card City Name

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#47]
I would propose to have the city name in the weather card (https://github.com/jimz011/homekit-infused/blob/master/docs/addons/weather-card.md) exposed to the user so that we can choose whether or not to fill out a city name. Personally, not having a city name in the card makes it look like it has a lot of empty space in the card.

Thanks!

https://github.com/bramkragten/weather-card

**Comment by jimz011** [comment]
No code change required for this, I've updated the docs and mentioned this. Closing now!
