### ISSUE TITLE
Cooling State Counter

### ISSUE THREAD

**Issue by righteousbs** [jimz011/homekit-infused#48]
Please include the cooling state when incrementing the climate counter.   See below for suggested update.

...packages/homekit_infused/hki_sensors.yaml
```
current_climate_entities_on:
        friendly_name: All Climate Entities Currently On
        value_template: >-
          {% set heat = states|selectattr('entity_id','in',state_attr('group.all_climate_entities','entity_id'))|selectattr('state','eq','heat')|list|count %}
          {% set cool = states|selectattr('entity_id','in',state_attr('group.all_climate_entities','entity_id'))|selectattr('state','eq','cool')|list|count %}
          {% set total = heat + cool %}
          {{total}}
```

**Comment by jimz011** [comment]
sounds fine by me, unfortunately I can't test it myself since I don't have cooling devices. However the code seems fine from what I can see here. I'll test at least if it is working. 

Expect this to be in the next update!

**Comment by jimz011** [comment]
added in 3.3.0 closing now!
