### ISSUE TITLE
[FR] Mini Graph Card In Lieu of More-Info

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#51]
Opening this to make a formal request that is easier to track.

Request: Have the mini-graph-card pop up on sensor entities instead of the current Home Assistant default of more-info.

Ex: I really liked the way this worked in HKI v2, with the nice looking graph and having the min, average, and max all displayed right there.

**Comment by jimz011** [comment]
I will add this back in the next update. I'll leave it open for now to remind me 😂

**Comment by jimz011** [comment]
Added in v3.4.0 closing now
