### ISSUE TITLE
[FR] Custom Header Replacement

### ISSUE THREAD

**Issue by ranrinc** [jimz011/homekit-infused#57]
**Is your feature request related to a problem? Please describe.**
Custom Header has been discontinued and we need a replacement need idea. Have been wanted to try your framework but tonight got stop due to custom header discontinued...

**Comment by jimz011** [comment]
A replacement is on the way. I will add it when custom header breaks. Since for now (HA 0.116.x) it still works fine.

I am still looking into a footer replacement since that is the only thing holding me back for now.

**Comment by jimz011** [comment]
Thanks for the issue report, this problem has been addressed and CH will be removed in the upcoming update (which will be somewhere in the next 24 hours).

The removal of CH affects this theme very little and aside from navigation no longer at the bottom everything stays the same.

Thank you for your patience. I will leave this issue open until the release.

**Comment by ranrinc** [comment]
Great news.. cant wait till I can begin migrating to your framework

**Comment by jimz011** [comment]
Fixed in 3.5.0. Closing now!
