### ISSUE TITLE
Package hki_configuration setup failed

### ISSUE THREAD

**Issue by roiahav** [jimz011/homekit-infused#58]
when i Configuration validation i receive an error.

Package hki_configuration setup failed. Integration frontend has duplicate key 'background-image' (See /config/packages/homekit_infused/hki_configuration.yaml:0).

**Comment by jimz011** [comment]
Seems like you've put the themes folder inside of the packages folder. Put the themes folder in the root of your HA install as instructed in the documentation.

Will close this since this is simply human error.
