### ISSUE TITLE
[ISSUE] Configuration provided gives check error.

### ISSUE THREAD

**Issue by DieterKoblenz** [jimz011/homekit-infused#61]
**Describe the bug**
Can't install this.

**Additional context**
Configuration was added:

Error loading /config/configuration.yaml: while scanning for the next token
found character '%' that cannot start any token
in "/config/integrations/base.yaml", line 18, column 14

**Comment by jimz011** [comment]
Did you install Lovelace_gen?

**Comment by DieterKoblenz** [comment]
> Did you install Lovelace_gen?

Doh. I did install it via HACS, did not restart yet though.

**Comment by DieterKoblenz** [comment]
I did now, still same problem.

**Comment by jimz011** [comment]
Ok, next question, do you have `lovelace_gen:` inside of your `configuration.yaml`? if `yes` then remove it!

**Comment by DieterKoblenz** [comment]
Nope,

this is my config.yaml:

`homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages/

lovelace:
  mode: storage
`

**Comment by jimz011** [comment]
Hm, your error message does not seem to be related to HKI though, I do not use the /integrations/ folder for this project, however your error does point to that. Could you please elaborate on what is in that folder exactly?

**Comment by DieterKoblenz** [comment]
Yes, it's the folder I use to add stuff like google_assistant.yaml, mqtt.yaml. 

So I copied base.yaml (and related subfolders) to integrations.

**Comment by jimz011** [comment]
base.yaml from HKI? because HKI only works if you keep the folder structure intact

**Comment by DieterKoblenz** [comment]
Yes, I copied the contents previously in homekit-infused to my "package" folder integrations.

**Comment by jimz011** [comment]
I'm guessing that is the reason it doesn't work as expected, as the documentation explains that you should not edit the folder structure or names but leave it as you find it on the repo. Also dropping `lovelace` files into your files where you store config like google_assistant and such is not a very good idea. You should keep config separated from lovelace.

**Comment by DieterKoblenz** [comment]
I'll try to separate the packages so to use two packages.

**Comment by jimz011** [comment]
You already use packages? If so what you can try to do is rename the folder you use to packages instead. And then throw the homekit-infused package (the one found in the packages folder). The homekit-infused folder found in the root should also be in your root as that is the lovelace package.

**Comment by DieterKoblenz** [comment]
I've tried several ways, but I couldn't get this to work at my current installation. Works fine on a clean installation as specified in the manual, but it's way too much effort atm to set up a clean installation. So I'll close this issue to keep clutter out of the way.
