### ISSUE TITLE
install problem[help]

### ISSUE THREAD

**Issue by litianyu0707** [jimz011/homekit-infused#67]
i install it in the hassio. the log:

2021-02-18 10:33:12 ERROR (MainThread) [homeassistant.config] Package hki_configuration setup failed. Integration lovelace_gen Integration 'lovelace_gen' not found. (See /config/packages/homekit_infused/hki_configuration.yaml:0).
2021-02-18 10:33:12 ERROR (MainThread) [homeassistant.config] Package hki_configuration setup failed. Integration browser_mod Integration 'browser_mod' not found. (See /config/packages/homekit_infused/hki_configuration.yaml:0).

the homekit infused can't load.

**Comment by jimz011** [comment]
Make sure you install browser_mod and lovelace_gen.

How to check?
1. Check the www/community folder if they are present
2. Check HACS if they are installed
3. Make sure the resources have been added to lovelace (settings > lovelace dashboards > resources)

**Comment by litianyu0707** [comment]
> Make sure you install browser_mod and lovelace_gen.
> 
> How to check?
> 
> 1. Check the www/community folder if they are present
> 2. Check HACS if they are installed
> 3. Make sure the resources have been added to lovelace (settings > lovelace dashboards > resources)

![1111](https://user-images.githubusercontent.com/22993989/108350284-02b68200-721f-11eb-85ff-ede15d6963a9.png)
![2222](https://user-images.githubusercontent.com/22993989/108350290-03e7af00-721f-11eb-95e1-a3c5f2a775fe.png)
![333](https://user-images.githubusercontent.com/22993989/108350530-47421d80-721f-11eb-89ee-68c9f4e38081.png)

i finished the step 1,2,3. but it  still have problem .

**Comment by jimz011** [comment]
Uh sorry I meant check the custom_components folder if there is browser mod and lovelace gen

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by litianyu0707** [comment]
> Uh sorry I meant check the custom_components folder if there is browser mod and lovelace gen Get Outlook for Android<https://aka.ms/ghei36>
> […](#)
> ________________________________ From: litianyu0707 <notifications@github.com> Sent: Thursday, February 18, 2021 12:27:27 PM To: jimz011/homekit-infused <homekit-infused@noreply.github.com> Cc: Jimmy Schings <jimz@live.nl>; Comment <comment@noreply.github.com> Subject: Re: [jimz011/homekit-infused] install problem[help] (#67) Make sure you install browser_mod and lovelace_gen. How to check? 1. Check the www/community folder if they are present 2. Check HACS if they are installed 3. Make sure the resources have been added to lovelace (settings > lovelace dashboards > resources) [1111]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350284-02b68200-721f-11eb-85ff-ede15d6963a9.png&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502912404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UROaAWuf5d6KAXHWfaJcAuhMniEsc9bTcTXTl8VGZv0%3D&reserved=0> [2222]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350290-03e7af00-721f-11eb-95e1-a3c5f2a775fe.png&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502922396%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y7CksJCNYEKcehUWZEipgpwcIsOmhNEC9tbpZWk36KM%3D&reserved=0> [333]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350530-47421d80-721f-11eb-89ee-68c9f4e38081.png&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502932393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=88VuQl6r6O0kmtaCPlN8M8PY%2BIffFdD1ydOM9qom%2BnE%3D&reserved=0> i finished the step 1,2,3. but it still have problem . — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjimz011%2Fhomekit-infused%2Fissues%2F67%23issuecomment-781277512&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502932393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=blYMo9dxTAcDl3uaZltgLYQxOFgD5Bdykr%2B%2FhY91fnQ%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALG6BXXORRDDHXFAEZ5F6HLS7T2R7ANCNFSM4XZPVGLQ&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502942390%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N08cafHM9IY57U1WZXEyBCQZ6a3Du0w6EnRKQPEQcqA%3D&reserved=0>.

there is only 'hacs'folder in  custom_components. what i should do?  thank you!

**Comment by jimz011** [comment]
You must install both lovelace_gen and browser-mod, you can do this from within HACS. After installing those you need to restart Home Assistant

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by litianyu0707** [comment]
> You must install both lovelace_gen and browser-mod, you can do this from within HACS. After installing those you need to restart Home Assistant Get Outlook for Android<https://aka.ms/ghei36>
> […](#)
> ________________________________ From: litianyu0707 <notifications@github.com> Sent: Thursday, February 18, 2021 12:39:10 PM To: jimz011/homekit-infused <homekit-infused@noreply.github.com> Cc: Jimmy Schings <jimz@live.nl>; Comment <comment@noreply.github.com> Subject: Re: [jimz011/homekit-infused] install problem[help] (#67) Uh sorry I meant check the custom_components folder if there is browser mod and lovelace gen Get Outlook for Androidhttps://aka.ms/ghei36<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fghei36&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518065775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uKS5BQF0ga0wNpoe02oxAdj3p%2FHe89hcQsXkQkK%2FZYk%3D&reserved=0> …
> ________________________________ From: litianyu0707 notifications@github.com<mailto:notifications@github.com> Sent: Thursday, February 18, 2021 12:27:27 PM To: jimz011/homekit-infused homekit-infused@noreply.github.com<mailto:homekit-infused@noreply.github.com> Cc: Jimmy Schings jimz@live.nl<mailto:jimz@live.nl>; Comment comment@noreply.github.com<mailto:comment@noreply.github.com> Subject: Re: [jimz011/homekit-infused] install problem[help] (#67<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjimz011%2Fhomekit-infused%2Fissues%2F67&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518075768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7ZWQ%2BTEFkx4uhxlmhlD2RPmPXS4IVE5eD50Tb%2BAb6yo%3D&reserved=0>) Make sure you install browser_mod and lovelace_gen. How to check? 1. Check the www/community folder if they are present 2. Check HACS if they are installed 3. Make sure the resources have been added to lovelace (settings > lovelace dashboards > resources) [1111]https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350284-02b68200-721f-11eb-85ff-ede15d6963a9.png&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502912404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UROaAWuf5d6KAXHWfaJcAuhMniEsc9bTcTXTl8VGZv0%3D&reserved=0<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350284-02b68200-721f-11eb-85ff-ede15d6963a9.png&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518075768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kV241kswh5Vx4j6xAprVnvWBaYtHyY3Zl457%2BK0smsA%3D&reserved=0> [2222]https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350290-03e7af00-721f-11eb-95e1-a3c5f2a775fe.png&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502922396%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y7CksJCNYEKcehUWZEipgpwcIsOmhNEC9tbpZWk36KM%3D&reserved=0<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350290-03e7af00-721f-11eb-95e1-a3c5f2a775fe.png&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518085765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RecLdPXhJJ2rxAgpBAaViGdvprJ%2B82wmfwtglimkHSA%3D&reserved=0> [333]https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350530-47421d80-721f-11eb-89ee-68c9f4e38081.png&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502932393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=88VuQl6r6O0kmtaCPlN8M8PY%2BIffFdD1ydOM9qom%2BnE%3D&reserved=0<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22993989%2F108350530-47421d80-721f-11eb-89ee-68c9f4e38081.png&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518085765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bUSZU5I2OjstT6sbH0QWgeG3CRmXGIgRhjJspP5ppq8%3D&reserved=0> i finished the step 1,2,3. but it still have problem . — You are receiving this because you commented. Reply to this email directly, view it on GitHubhttps://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjimz011%2Fhomekit-infused%2Fissues%2F67%23issuecomment-781277512&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502932393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=blYMo9dxTAcDl3uaZltgLYQxOFgD5Bdykr%2B%2FhY91fnQ%3D&reserved=0<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjimz011%2Fhomekit-infused%2Fissues%2F67%23issuecomment-781277512&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518095752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iYFFS93uRrZwn56T4MvA5SBYEn%2FDEdNkPaFAjkY0HIY%3D&reserved=0>, or unsubscribehttps://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALG6BXXORRDDHXFAEZ5F6HLS7T2R7ANCNFSM4XZPVGLQ&data=04%7C01%7C%7C1c76c8d004c64617376208d8d4002cd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492444502942390%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N08cafHM9IY57U1WZXEyBCQZ6a3Du0w6EnRKQPEQcqA%3D&reserved=0<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALG6BXXORRDDHXFAEZ5F6HLS7T2R7ANCNFSM4XZPVGLQ&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518105745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JWG%2BPc4OGHBxgwvdZH54r56RI98Myb71juxP9birm%2BI%3D&reserved=0>. there is only 'hacs'folder in custom_components. what i should do? thank you! — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjimz011%2Fhomekit-infused%2Fissues%2F67%23issuecomment-781283294&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518105745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=brdt5ydJBM3QR1PysMU47HYuOUZxo223i2tpTl7MV9E%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALG6BXQMD7HCUUKWKBFXFBDS7T355ANCNFSM4XZPVGLQ&data=04%7C01%7C%7C3970a9396de94225e08308d8d401cf27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637492451518115744%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T95ND7BjphN1%2Fq0031LGBJUW%2Fo4rhsJ5wERK5dE3Mfc%3D&reserved=0>.

Wow!!!  it works, thank you!    hope you have a nice day !

**Comment by jimz011** [comment]
After that, check if they are present in the custom components folder

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jimz011** [comment]
You are most welcome
