### ISSUE TITLE
[FR] Hide subtitle & icon via the header_config.yaml for certain pages

### ISSUE THREAD

**Issue by evroekel** [jimz011/homekit-infused#70]
**Is your feature request related to a problem? Please describe.**
With the new navigation bar the subtitles in the header_config.yaml feels often as an overkill for me with no added value.

**Describe the solution you'd like**
I would like to be able to hide the subtitle and icon on certain pages. 

**Describe alternatives you've considered**
Tried to just leave it blank in the header_config.yaml but that didn't work.

**Additional context**
On some pages I do use the subtitle i.e. to display average temp indoor/outdoor on the Climate page.  So a general setting the hide/unhide on all pages wouldn't suite my case.

**Comment by jimz011** [comment]
Making it conditional for every view is what I have done in the past and would take a big hit on performance. I will try to implement your request, though I am not certain if I can make it on a per view basis. A general disable would be less of a hit on performance and is something I can do for certain.

I will let you know how this progresses, but for now don't expect a per view basis.

**Comment by evroekel** [comment]
No hurry.. I just found a workaround :-)

`media_title: Media
  media_subtitle: "[[[ return ``; ]]]"
 
  media_icon: `

leaves the subtitle blank including the icon. And so far no errors ;-)

**Comment by jimz011** [comment]
I will close this issue as this will be possible in the upcoming version!
