### ISSUE TITLE
[ISSUE] Alarm icon spacing

### ISSUE THREAD

**Issue by evroekel** [jimz011/homekit-infused#71]
<img width="220" alt="Schermafbeelding 2021-04-07 om 19 45 51" src="https://user-images.githubusercontent.com/57673156/113911268-153e4800-97da-11eb-9cd6-e6b436e36e18.png">

**Describe the bug**
Minor, minor issue... but the alarm icon seems to miss some space below. 

<img width="995" alt="Schermafbeelding 2021-04-07 om 20 01 36" src="https://user-images.githubusercontent.com/57673156/113913076-2daf6200-97dc-11eb-83b0-e70daed5d56d.png">

When there's a notification the spacing is fine. It looks a like the height of the section without the notification is a couple of pixels too small. 

**Current Running Home Assistant version:**
2021.3.4

**Device HA running on and client device viewing lovelace:**
Safari on a Mac & and latest HA app on iPhone 11

**Comment by jimz011** [comment]
Closing this now since it is fixed in the upcoming version!
