### ISSUE TITLE
Multiple Alarms

### ISSUE THREAD

**Issue by DerHerzog7** [jimz011/homekit-infused#73]
Is there a way to list multiple alarm control panels? As far as I can tell you can only include one in the configuration. 

**Home Assistant version: 2021.4.6**
**HKI Version 4.0.0b**

**Comment by jimz011** [comment]
No, you can only enter a single one, however you could make a view with your own alarm control panels.

Could you maybe give me an example of what you want and how you think it should have been? Maybe I can do something for you.

**Comment by DerHerzog7** [comment]
All good. I have my alarm set for my Cameras - the doorbell is a separate "alarm." Apparently, Arlo is incorporating it into the base hub eventually, so probably unnecessary. And, to be honest, I could probably just create an automation to do it for me.

**Comment by jimz011** [comment]
Possible in HKI 5, will close this now
