### ISSUE TITLE
show_in_favorites: false not working? (v4.0.0c Beta)

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#75]
With these settings security is still shown in my favorites after reloading. Bug? 

<img width="454" alt="favo" src="https://user-images.githubusercontent.com/57673156/115556523-10d15f00-a2b1-11eb-8a08-96d866fc5899.png">

**Comment by jimz011** [comment]
First, did you restart? Since any changes in that file requires a restart.

If that still doesnt work, just remove the show_in_favorites line all together

**Comment by E020** [comment]
I did a restart, but same result. 
Removing the whole line solved it, but not quit as supposed to be this workaround ;-)

**Comment by jimz011** [comment]
Well its a beta so you will find bugs everywhere, I will add more conditions so that this won't be an issue in the future.

Thanks
