### ISSUE TITLE
[FR] button cards on home

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#76]
I do like the setup with views. But besides links to a Generic or Custom view I would like to be able to add buttons on home  to be able to turn a light on/off, right away on the home itself. 

I know this can be done by adding a yaml file in the home subdirectory, but it would be nice to set this up in the view_config also, in some custom section.

<img width="720" alt="home" src="https://user-images.githubusercontent.com/57673156/115914044-afa4b980-a471-11eb-9467-633abbf92c69.png">

**Comment by jimz011** [comment]
The next update has its frontpage and menu reworked and can now use all the addons that are available. Just set it up as your standard views.

**Comment by jimz011** [comment]
Closing this since this is now possible in v4.0.0d
