### ISSUE TITLE
Grid Error

### ISSUE THREAD

**Issue by DerHerzog7** [jimz011/homekit-infused#80]
Just updated to the latest beta (d) and now I am getting the following error:

![image](https://user-images.githubusercontent.com/60498810/116834968-d39b9400-ac03-11eb-9dc4-ddf8d231159d.png)

Any ideas?

**Comment by jimz011** [comment]
You need to redo the frontpage as mentioned in the breaking changes. I hope that helps

**Comment by DerHerzog7** [comment]
Yeh I did. I'm getting this error even after a full reinstall...

**Comment by jimz011** [comment]
Could you share me your view config?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jimz011** [comment]
Question, did you setup any views? If not please do that first. If yes, did you add any as favorite? If no, either add one to favorites, or... remove favorites from the frontpage in view config.

**Comment by jimz011** [comment]
Closing this since it was a bug only present on new installs.

**Comment by DerHerzog7** [comment]
Oh did you release an update?

**Comment by jimz011** [comment]
Well, yes and no. I only edited the file for new users. Since it doesn't matter for anyone who already installed this. To make the first card work on your frontpage you must have at least 1 single view with `show_in_favorites: true`.

**Comment by DerHerzog7** [comment]
Oh ok! Well I need to set it up fresh anyway. I screwed something up with "updating"
