### ISSUE TITLE
Button Icon Colors

### ISSUE THREAD

**Issue by JustFxDev** [jimz011/homekit-infused#82]
The icon colors for a button (button-bage.yaml e. g.) are not conistent and not complete setable from a view.

I would like to suggest to have

for button state 'on'
```
      # ICON COLOR ON
      icon:
        - color: {{ icon_color_on|default('var(--button-on-icon-color)') }}
```

for button state 'off'
```
      # ICON COLOR OFF
      icon:
        - color: {{ icon_color_off|default('var(--button-off-icon-color)') }}
```

for button state 'default
```

      # ICON COLOR DEFAULT
      icon:
        - color: {{ icon_color_default|default('var(--button-default-icon-color)') }}
```

If it applies to a specific button. All button template should have this definitions.

This would allow to define a specific icon color per button and furthermore make the icon color definitions more consistent. For e. g. in button-bage.yaml the "off" color is definined in the "default" section and the "off" section has no definition. Furthermore this allows better "themeing"

I attach a file with a complete version of button-badge.yaml with the changes.

Keep up the great work! Thank you!

[button-badge.zip](https://github.com/jimz011/homekit-infused/files/6420726/button-badge.zip)

**Comment by jimz011** [comment]
I will certainly take a look at this, since theming has been on a long list of todo's (and theming is hard, takes a long time and has a bit of a lower priority).

Thanks for the input, I will leave this issue open for now so I will be remembered.

**Comment by jimz011** [comment]
This is already possible with the current custom addon (and will also be possible in HKI 5) closing this issue now!
