### ISSUE TITLE
Persons state error and weather card

### ISSUE THREAD

**Issue by DerHerzog7** [jimz011/homekit-infused#83]
I can't for the life of me figure out why I am getting the errors in the picture below. The Home or Away states were showing in V3. Also, the weather/simple weather card won't show. (ignore the bar - that only occurred cause I scrolled while taking a screenshot). 

![image](https://user-images.githubusercontent.com/60498810/117086987-8d743b00-ad91-11eb-89d1-f0beddd94141.png)

**Comment by Russell-A-Diehl** [comment]
I had the same issue for the persons card moving from 4.0.0c to 4.0.0d; maybe check your config for the following.

```
persons:
  me:
    person_entity: person.me
```
needs changed to 
```
persons:
  me:
    entity: person.me
```

As for the weather card, I had some minor issues in the latest beta with the view refactoring and weather cards now being an addon but was able to solve it reading through the updated documentation.

**Comment by DerHerzog7** [comment]
> I had the same issue for the persons card moving from 4.0.0c to 4.0.0d; maybe check your config for the following.
> 
> ```
> persons:
>   me:
>     person_entity: person.me
> ```
> 
> needs changed to
> 
> ```
> persons:
>   me:
>     entity: person.me
> ```
> 
> As for the weather card, I had some minor issues in the latest beta with the view refactoring and weather cards now being an addon but was able to solve it reading through the updated documentation.

Ah sweet! I somehow missed that change. Person state is fixed.

I've worked through all the documentation for both simple weather and the standard weather card. It still not showing anything. I DID managed to get it from "Unknown" to the weather type ie/ Sunny (was using the wrong weather sensor), but still showing the broken image.

**Comment by DerHerzog7** [comment]
Ok I did some digging. It seems _anything_ I list underneath the "persons" section of the Homescreen, results in the broken tile. I had to put the weather, favourites etc above persons. Also, the search card doesn't seem to appear in the homescreen.

Might be something to note for the V4 release?

**Comment by jimz011** [comment]
It depends on indentation. So if your simple weather addon was indented under the persons object it wouldn't work. Indentation is one of the most common mistakes and is unfortunately how yaml works.

I will soon make some videos to explain this better since I am positive that a single video will help you understand.

**Comment by DerHerzog7** [comment]
> It depends on indentation. So if your simple weather addon was indented under the persons object it wouldn't work. Indentation is one of the most common mistakes and is unfortunately how yaml works.
> 
> I will soon make some videos to explain this better since I am positive that a single video will help you understand.

Yeh I thought of that and triple checked the indentation. I even went so far as copy-pasting your sample and tweaking for my set up. Same issue.

**Comment by DerHerzog7** [comment]
> It depends on indentation. So if your simple weather addon was indented under the persons object it wouldn't work. Indentation is one of the most common mistakes and is unfortunately how yaml works.
> 
> I will soon make some videos to explain this better since I am positive that a single video will help you understand.

Yeh I thought of that and triple checked the indentation. I even went so far as copy-pasting your sample and tweaking for my set up. Same issue.

**Comment by jimz011** [comment]
Do you by any chance have `view_config:` twice? It should only be at the top of the page

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by DerHerzog7** [comment]
Just checked - it's only there once. 
It's all good - I just put weather at the top
Any idea why Search isn't showing?

**Comment by jimz011** [comment]
please share your view_config

**Comment by DerHerzog7** [comment]
See attached,

Search card definitely isnt working. I even added it as it's own View, and it doesn't show.


[view_config.txt](https://github.com/jimz011/homekit-infused/files/6431094/view_config.txt)

**Comment by Russell-A-Diehl** [comment]
> See attached,
> 
> Search card definitely isnt working. I even added it as it's own View, and it doesn't show.
> 
> [view_config.txt](https://github.com/jimz011/homekit-infused/files/6431094/view_config.txt)

Just a guess but maybe try removing the line beginning with show_title: right above search_card. Or change it to show_subtitle: false.

show_title doesn’t appear to be a valid top level config item according to the documentation so it may be causing the error?

Does the search card work in your menu view?

**Comment by DerHerzog7** [comment]
Ok, I'll try that. No it doesn't work in search view...

**Comment by jimz011** [comment]
Yup it seems like I made a few typos on the search card

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by DerHerzog7** [comment]
No stress. This is what a Beta is for!

**Comment by jimz011** [comment]
These errors should have been fixed with the latest beta v.4.0.0e
