### ISSUE TITLE
[FR] Input.boolean button without pop-up

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#85]
I have several aantal input.booleans that when clicked trigger an automation that turns several entities off (lights, heating, TV etc). In the previous it was a button without a pop-up. In the beta it gives a pop-up when clicked and within that pop-up there's the switch to turn it on/off. 

I would like to have this without the pop-up. So clicking the button immediately turn the boolean on/off. I don't think it possible, yet. Correct?

**Comment by jimz011** [comment]
Yup these will all be fixed, I am rewriting the devices addon and will split them up into lights, switches, sensors, binary sensors, graphs and covers. They will all become separate addons with tons of new options (e.g. setting icon and friendly name without customize.yaml)

This will take some time though

**Comment by jimz011** [comment]
I will leave this a bit open for now, since I am not exactly sure it this is possible now in v4.0.0e. But you should check it out and try.

**Comment by E020** [comment]
with type: switch it works!
