### ISSUE TITLE
[FR] Preset buttons Climate resizable

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#86]
When show_cool, show_heat and show_set_temperature are set to false, the remaining buttons become pretty big and resizing seems impossible. Would be nice to somehow resize these buttons in situations like this.

**Comment by jimz011** [comment]
This was already an issue, though, in beta 5 you will be able to adjust the aspect ratio

**Comment by E020** [comment]
I know, but I saw your request to send in FR via Github so you have better overview. No hurry...

**Comment by jimz011** [comment]
Well it definitely is easier for me to keep track of the requests and issues this way than to scroll down endless messages on discord 🤣, this is greatly appreciated

**Comment by jimz011** [comment]
This issue has been fixed in v4.0.0e
