### ISSUE TITLE
[FR] Hide (some of the) Vacuum features

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#87]
I have a Roomba without the option for fanspeed or mopping. Just these options:

<img width="378" alt="Schermafbeelding 2021-05-09 om 16 47 38" src="https://user-images.githubusercontent.com/57673156/117576445-55992a80-b0e6-11eb-8ced-c194f43529d8.png">

Would be nice to somehow disable/hide some options in the current card:
<img width="503" alt="Schermafbeelding 2021-05-09 om 16 49 13" src="https://user-images.githubusercontent.com/57673156/117576570-c2acc000-b0e6-11eb-875e-ee65d39e5cea.png">

And if the second row is hidden it would be nice to resize the remaining buttons to the regular size.

**Comment by jimz011** [comment]
It is already possible to hide the mopping button

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: E020 ***@***.***>
Sent: Sunday, May 9, 2021 4:50:57 PM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] [FR] Hide (some of the) Vacuum features (#87)


I have a Roomba without the option for fanspeed or mopping. Just these options:

[Schermafbeelding 2021-05-09 om 16 47 38]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F57673156%2F117576445-55992a80-b0e6-11eb-8ced-c194f43529d8.png&data=04%7C01%7C%7C31e968f83dab4f41eb9e08d912f9db7a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637561686594409589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g3uiJd%2FTvxiXKNxhPKQf32a%2BKuj%2FQAMEi9DMz%2BMbFdk%3D&reserved=0>

Would be nice to somehow disable/hide some options.

**Comment by jimz011** [comment]
Closing this issue since this is now possible in v4.0.0e
