### ISSUE TITLE
Media Players Sensor

### ISSUE THREAD

**Issue by DerHerzog7** [jimz011/homekit-infused#88]
I'm trying to set up my media players similar to your set up.

Where does the sensor.media_players_playing sensor come from?

**Comment by NewOakley** [comment]
I have create a template sensor, like he did in version 3. with the if / else construction als sensor. He has the state playing and pause but so far i know this depends on your kind of media player. Some media players coul have addition statusses.

**Comment by DerHerzog7** [comment]
Ah ok. Didn't even occur to me to make a template one...

**Comment by DerHerzog7** [comment]
> I have create a template sensor, like he did in version 3. with the if / else construction als sensor. He has the state playing and pause but so far i know this depends on your kind of media player. Some media players coul have addition statusses.

Do you have an example of what the YAML would look like for this?

**Comment by NewOakley** [comment]
```
media_players_playing:
        value_template: >
          {% if states.media_player.apple_tv.state == 'playing' %}
            Playing
          {% elif states.media_player.denon_avr_x2400h_2.state == 'playing' %}
            Playing
          {% elif states.media_player.spotify_newoakley.state == 'playing' %}
            Playing
          {% elif states.media_player.playstation_4.state == 'playing' %}
            Playing
          {% elif states.media_player.tv == 'playing' %}
            Playing
          {% elif states.media_player.apple_tv.state == 'paused' %}
            Paused
          {% elif states.media_player.denon_avr_x2400h_2.state == 'paused' %}
            Paused
          {% elif states.media_player.spotify_newoakley.state == 'paused' %}
            Paused
          {% elif states.media_player.playstation_4.state == 'paused' %}
            Paused
          {% elif states.media_player.tv == 'paused' %}
            Paused
          {% else %}
            Not Playing
          {% endif %}
```
At the top you have to use 
```
- platoform: template
   sensors:
      your_media_sensor_as_above:
```

**Comment by jimz011** [comment]
What @NewOakley shows here is exactly how I have setup my sensor as well. I will not add this feature since it is too hard to template it, also the use of these kind of sensors is for a very select people that want this. The majority will never even think of this.
