### ISSUE TITLE
FR: set the opacity_off for buttons

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#91]
In version 3 it was possible to set opacity_off to 1.0. In V4 this doesn't seem possible anymore. I would like to be able to set it to 1.0 completely opaque again. The show state is already there, changing the transparency is a bit too much for me. 

    devices:
      - title:
        show_title: false
        entities:
          - light.bank
            opaque_off: 1.0

**Comment by jimz011** [comment]
I can add that, though the show_title line doesnt work anymore.

In  this case you should just start with - entities

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: E020 ***@***.***>
Sent: Sunday, May 16, 2021 3:57:11 PM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] FR: set the opacity_off for buttons (#91)


In version 3 it was possible to set opacity_off to 1.0. In V4 this doesn't seem possible anymore. I would like to be able to set it to 1.0 completely opaque again. The show state is already there, changing the transparency is a bit too much for me.

devices:
  - title:
    show_title: false
    entities:
      - light.bank
        opaque_off: 1.0

**Comment by E020** [comment]
Corrected the title / show_title in the meantime, thx. Would be nice to have the opaque setting again.

**Comment by jimz011** [comment]
this change has been added in the RC, closing this now
