### ISSUE TITLE
[FR] Support all options for mini media player

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#96]
I would like to get rid of my customs view for media players. But I'm using several options of https://github.com/kalkih/mini-media-player that are not yet available at https://jimz011.github.io/homekit-infused/addons-v4/media-players.html. 

Like tts, speaker group, hide etc. 

Are these somewhere on your roadmap?

Here's an example of my current settings with the options:

- type: custom:mini-media-player
  entity: media_player.woonkamer
  info: short
  artwork: cover
  tts:
    platform: google_translate
    language: nl
  hide:
    mute: true
    icon: true
    power_state: false
  speaker_group:
    platform: sonos
    show_group_count: true
    entities:
      - entity_id: media_player.woonkamer
        name: Woonkamer
      - entity_id: media_player.keuken
        name: Keuken
      - entity_id: media_player.XXX
        name: XXX
      - entity_id: media_player.YYY
        name: YYY
      - entity_id: media_player.ZZZ
        name: ZZZ

**Comment by 2wenty2wo** [comment]
Being able to hide would be great.

**Comment by jimz011** [comment]
This will be possible in HKI 5 (or with the current custom addon), closing this issue!
