### ISSUE TITLE
YAML file /config/hki-base/base.yaml contains duplicate key "entity". Check lines 2734 and 2736

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#97]
<img width="694" alt="Schermafbeelding 2021-05-23 om 12 50 28" src="https://user-images.githubusercontent.com/57673156/119257460-97859e80-bbc5-11eb-8dc7-339b701346b8.png">

**Comment by jimz011** [comment]
This is a known issue and is caused by the battery addon. I have already fixed this and will be pushed in the next update.
