### ISSUE TITLE
[FR] Markdown Card as an Add-on

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#98]
I would love to see the generic lovelace markdown card could be brought in as a fully supported add-on. Right now to have a markdown card in a view I must make a custom view but it would be much more seamless if the markdown card was brought in as an official add-on.

I don't know how extensive the card options could be though since a lot of the formatting of the markdown card happens by the amount of empty lines and ** (asterisks) are used. But even a simple card that only allows for a single paragraph at one text size would be great.

**Comment by jimz011** [comment]
I am fairly sure that this is impossible, unless the user would use an included file that contains the multiline code they want in their markdown card. But I will look into making it possible in some way, I can't promise anything here though as just like the entities card this card is pretty powerful in itself.

**Comment by MagicMountainMan** [comment]
Using an !include is actually a pretty good idea I think that could actually work with relatively minimal effort on your end.

**Comment by jimz011** [comment]
This will be possible soon, without the necessary includes as mentioned earlier!

**Comment by jimz011** [comment]
This is already possible through the custom: addon
